// The curated background photos (files under ./library/backgrounds).
import type { MediaCredit } from './media';

export const BACKGROUND_LIBRARY: MediaCredit[] = [
  {
    id: 'forest-sea',
    title: 'Forest & Sea',
    author: 'Paul Jarvis',
    license: 'Unsplash (via Lorem Picsum)',
    sourceUrl: 'https://unsplash.com/photos/6J--NXulQCs',
    file: 'forest-sea.jpg',
  },
  {
    id: 'desk-flatlay',
    title: 'Desk Flatlay',
    author: 'Aleks Dorohovich',
    license: 'Unsplash (via Lorem Picsum)',
    sourceUrl: 'https://unsplash.com/photos/nJdwUHmaY8A',
    file: 'desk-flatlay.jpg',
  },
  {
    id: 'green-forest',
    title: 'Green Forest',
    author: 'Jerry Adney',
    license: 'Unsplash (via Lorem Picsum)',
    sourceUrl: 'https://unsplash.com/photos/_WiFMBRT7Aw',
    file: 'green-forest.jpg',
  },
  {
    id: 'rocky-coast',
    title: 'Rocky Coast',
    author: 'Austin Neill',
    license: 'Unsplash (via Lorem Picsum)',
    sourceUrl: 'https://unsplash.com/photos/erTjj730fMk',
    file: 'rocky-coast.jpg',
  },
  {
    id: 'laptop-desk',
    title: 'Laptop Desk',
    author: 'Luke Chesser',
    license: 'Unsplash (via Lorem Picsum)',
    sourceUrl: 'https://unsplash.com/photos/1uxV8fAfhVM',
    file: 'laptop-desk.jpg',
  },
  {
    id: 'golden-hour',
    title: 'Golden Hour',
    author: 'Alexander Shustov',
    license: 'Unsplash (via Lorem Picsum)',
    sourceUrl: 'https://unsplash.com/photos/2FrX56QL7P8',
    file: 'golden-hour.jpg',
  },
  {
    id: 'neon-alley',
    title: 'Neon Alley',
    author: 'masahiro miyagi',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/mGs7oMPLB-c',
    file: 'neon-alley.jpg',
  },
  {
    id: 'warm-bokeh',
    title: 'Warm Bokeh',
    author: 'Md Mahdi',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/lmlfo8aespo',
    file: 'warm-bokeh.jpg',
  },
  {
    id: 'pastel-gradient',
    title: 'Pastel Gradient',
    author: 'Codioful',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/LeG68PrXA6Y',
    file: 'pastel-gradient.jpg',
  },
  {
    id: 'sage-wall',
    title: 'Sage Wall',
    author: 'David van Dijk',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/3LTht2nxd34',
    file: 'sage-wall.jpg',
  },
  {
    id: 'snowy-peak',
    title: 'Snowy Peak',
    author: 'Rohit Tandon',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/9wg5jCEPBsw',
    file: 'snowy-peak.jpg',
  },
  {
    id: 'desert-dunes',
    title: 'Desert Dunes',
    author: 'Zetong Li',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/HEf0fKgJA1Q',
    file: 'desert-dunes.jpg',
  },
  {
    id: 'turquoise-sea',
    title: 'Turquoise Sea',
    author: 'samsommer',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/J3ABLQjZQBg',
    file: 'turquoise-sea.jpg',
  },
  {
    id: 'cafe-table',
    title: 'Café Table',
    author: 'Kris Atomic',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/3b2tADGAWnU',
    file: 'cafe-table.jpg',
  },
  {
    id: 'concrete-lines',
    title: 'Concrete Lines',
    author: 'Lukas S',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/ejGv_enkOBY',
    file: 'concrete-lines.jpg',
  },
  {
    id: 'milky-way',
    title: 'Milky Way',
    author: 'Dns Dgn',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/9wH624ALFQA',
    file: 'milky-way.jpg',
  },
  {
    id: 'autumn-leaves',
    title: 'Autumn Leaves',
    author: 'Jeremy Thomas',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/O6N9RV2rzX8',
    file: 'autumn-leaves.jpg',
  },
  {
    id: 'monstera-leaves',
    title: 'Monstera Leaves',
    author: 'Natalie Kovach',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/ph7QQq63lCs',
    file: 'monstera-leaves.jpg',
  },
  {
    id: 'rainy-window',
    title: 'Rainy Window',
    author: 'C. G.',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/JgDUVGAXsso',
    file: 'rainy-window.jpg',
  },
  {
    id: 'pink-sunset',
    title: 'Pink Sunset',
    author: 'Diego PH',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/BCuxVP5WEsU',
    file: 'pink-sunset.jpg',
  },
  {
    id: 'woodshop',
    title: 'Woodshop',
    author: 'Bailey Alexander',
    license: 'Unsplash',
    sourceUrl: 'https://unsplash.com/photos/Yl7YJcUn_Oo',
    file: 'woodshop.jpg',
  },
];
