// Single source of truth for the curated media library, shared by web + expo.
// Assets live under ./library/musics and ./library/backgrounds and are copied
// into each app's static dir by scripts/copy-core-assets.ts at build/dev time.
export interface MediaCredit {
  id: string;
  title: string;
  author: string;
  license: string;
  sourceUrl: string;
  file: string; // filename only, e.g. 'point-being.mp3'
}

export const MUSIC_LIBRARY: MediaCredit[] = [
  {
    id: 'point-being',
    title: 'Point Being',
    author: 'Go By Ocean / Ryan McCaffrey',
    license: 'YouTube Audio Library (no attribution required)',
    sourceUrl: 'https://www.youtube.com/audiolibrary',
    file: 'point-being.mp3',
  },
  {
    id: 'americana',
    title: 'Americana',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100254',
    file: 'americana.mp3',
  },
  {
    id: 'arcadia',
    title: 'Arcadia',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100291',
    file: 'arcadia.mp3',
  },
  {
    id: 'anxiety',
    title: 'Anxiety',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100288',
    file: 'anxiety.mp3',
  },
  {
    id: 'air-prelude',
    title: 'Air Prelude',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100337',
    file: 'air-prelude.mp3',
  },
  {
    id: 'tropical-cocktail',
    title: 'Tropical Cocktail',
    author: 'The_Mountain',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/pop-tropical-cocktail-159121/',
    file: 'tropical-cocktail.mp3',
  },
  {
    id: 'autumn-day',
    title: 'Autumn Day',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100765',
    file: 'autumn-day.mp3',
  },
  {
    id: 'monkeys-spinning-monkeys',
    title: 'Monkeys Spinning Monkeys',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Monkeys%20Spinning%20Monkeys.mp3',
    file: 'monkeys-spinning-monkeys.mp3',
  },
  {
    id: 'fluffing-a-duck',
    title: 'Fluffing a Duck',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fluffing%20a%20Duck.mp3',
    file: 'fluffing-a-duck.mp3',
  },
  {
    id: 'sneaky-snitch',
    title: 'Sneaky Snitch',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Sneaky%20Snitch.mp3',
    file: 'sneaky-snitch.mp3',
  },
  {
    id: 'carefree',
    title: 'Carefree',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Carefree.mp3',
    file: 'carefree.mp3',
  },
  {
    id: 'pixelland',
    title: 'Pixelland',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Pixelland.mp3',
    file: 'pixelland.mp3',
  },
  {
    id: 'the-builder',
    title: 'The Builder',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/The%20Builder.mp3',
    file: 'the-builder.mp3',
  },
  {
    id: 'brain-dance',
    title: 'Brain Dance',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Brain%20Dance.mp3',
    file: 'brain-dance.mp3',
  },
  {
    id: 'local-forecast-elevator',
    title: 'Local Forecast - Elevator',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Local%20Forecast%20-%20Elevator.mp3',
    file: 'local-forecast-elevator.mp3',
  },
  {
    id: 'lofi-sentimental-jazz',
    title: 'Lo-fi Sentimental Jazz',
    author: 'Sonican',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/lofi-lo-fi-music-loop-sentimental-jazzy-love-473154/',
    file: 'lofi-sentimental-jazz.mp3',
  },
  {
    id: 'cafe-bossa-nova',
    title: 'Cafe Bossa Nova',
    author: 'rediskasound',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/bossa-nova-cafe-bossa-nova-554525/',
    file: 'cafe-bossa-nova.mp3',
  },
  {
    id: 'lofi-chill',
    title: 'Lo-fi Chill',
    author: 'AtlasAudio',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/lofi-chill-519566/',
    file: 'lofi-chill.mp3',
  },
  {
    id: 'lofi-hip-hop',
    title: 'Lo-fi Hip-Hop',
    author: 'leberch',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/lofi-lofi-hip-hop-519408/',
    file: 'lofi-hip-hop.mp3',
  },
  {
    id: 'party-dance',
    title: 'Party Dance',
    author: 'prettyjohn1',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/dance-party-dance-526227/',
    file: 'party-dance.mp3',
  },
  {
    id: 'future-bass-energy',
    title: 'Future Bass Energy',
    author: 'BombinSound',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/future-bass-energetic-upbeat-future-bass-version-1-537886/',
    file: 'future-bass-energy.mp3',
  },
  {
    id: 'upbeat-electronic',
    title: 'Upbeat Electronic',
    author: 'prettyjohn1',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/electro-upbeat-513865/',
    file: 'upbeat-electronic.mp3',
  },
  {
    id: 'indie-rock-dreamy',
    title: 'Indie Rock Dreamy',
    author: 'alex-morgan',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/rock-indie-rock-dreamy-537459/',
    file: 'indie-rock-dreamy.mp3',
  },
  {
    id: 'cafe-jazz',
    title: 'Peaceful Cafe Jazz',
    author: 'alex-morgan',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/beats-peaceful-cafe-jazz-relaxing-coffee-shop-541031/',
    file: 'cafe-jazz.mp3',
  },
  {
    id: 'romantic-piano',
    title: 'Romantic Piano',
    author: 'TolsetMusic',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/beautiful-plays-talking-about-love-romantic-piano-background-music-542958/',
    file: 'romantic-piano.mp3',
  },
];

export const BACKGROUND_LIBRARY: MediaCredit[] = [
  {
    id: 'forest-sea',
    title: 'Forest & Sea',
    author: 'Paul Jarvis',
    license: 'Unsplash (via Lorem Picsum)',
    sourceUrl: 'https://unsplash.com/photos/6J--NXulQCs',
    file: 'forest-sea.jpg',
  },
  {
    id: 'desk-flatlay',
    title: 'Desk Flatlay',
    author: 'Aleks Dorohovich',
    license: 'Unsplash (via Lorem Picsum)',
    sourceUrl: 'https://unsplash.com/photos/nJdwUHmaY8A',
    file: 'desk-flatlay.jpg',
  },
  {
    id: 'green-forest',
    title: 'Green Forest',
    author: 'Jerry Adney',
    license: 'Unsplash (via Lorem Picsum)',
    sourceUrl: 'https://unsplash.com/photos/_WiFMBRT7Aw',
    file: 'green-forest.jpg',
  },
  {
    id: 'rocky-coast',
    title: 'Rocky Coast',
    author: 'Austin Neill',
    license: 'Unsplash (via Lorem Picsum)',
    sourceUrl: 'https://unsplash.com/photos/erTjj730fMk',
    file: 'rocky-coast.jpg',
  },
  {
    id: 'laptop-desk',
    title: 'Laptop Desk',
    author: 'Luke Chesser',
    license: 'Unsplash (via Lorem Picsum)',
    sourceUrl: 'https://unsplash.com/photos/1uxV8fAfhVM',
    file: 'laptop-desk.jpg',
  },
  {
    id: 'golden-hour',
    title: 'Golden Hour',
    author: 'Alexander Shustov',
    license: 'Unsplash (via Lorem Picsum)',
    sourceUrl: 'https://unsplash.com/photos/2FrX56QL7P8',
    file: 'golden-hour.jpg',
  },
];

export const findMusic = (id: string): MediaCredit | undefined => MUSIC_LIBRARY.find((m) => m.id === id);
export const findBackground = (id: string): MediaCredit | undefined => BACKGROUND_LIBRARY.find((m) => m.id === id);
