// The curated music tracks (files under ./library/musics, cover art under ./library/covers).
import type { MediaCredit } from './media';

export const MUSIC_LIBRARY: MediaCredit[] = [
  {
    id: 'point-being',
    title: 'Point Being',
    author: 'Go By Ocean / Ryan McCaffrey',
    license: 'YouTube Audio Library (no attribution required)',
    sourceUrl: 'https://www.youtube.com/audiolibrary',
    file: 'point-being.mp3',
  },
  {
    id: 'tropical-cocktail',
    title: 'Tropical Cocktail',
    author: 'The_Mountain',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/pop-tropical-cocktail-159121/',
    file: 'tropical-cocktail.mp3',
  },
  {
    id: 'autumn-day',
    title: 'Autumn Day',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/index.html?isrc=USUAN1100765',
    file: 'autumn-day.mp3',
  },
  {
    id: 'monkeys-spinning-monkeys',
    title: 'Monkeys Spinning Monkeys',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Monkeys%20Spinning%20Monkeys.mp3',
    file: 'monkeys-spinning-monkeys.mp3',
  },
  {
    id: 'fluffing-a-duck',
    title: 'Fluffing a Duck',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Fluffing%20a%20Duck.mp3',
    file: 'fluffing-a-duck.mp3',
  },
  {
    id: 'carefree',
    title: 'Carefree',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Carefree.mp3',
    file: 'carefree.mp3',
  },
  {
    id: 'the-builder',
    title: 'The Builder',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/The%20Builder.mp3',
    file: 'the-builder.mp3',
  },
  {
    id: 'local-forecast-elevator',
    title: 'Local Forecast - Elevator',
    author: 'Kevin MacLeod',
    license: 'CC BY 3.0',
    sourceUrl: 'https://incompetech.com/music/royalty-free/mp3-royaltyfree/Local%20Forecast%20-%20Elevator.mp3',
    file: 'local-forecast-elevator.mp3',
  },
  {
    id: 'lofi-sentimental-jazz',
    title: 'Lo-fi Sentimental Jazz',
    author: 'Sonican',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/lofi-lo-fi-music-loop-sentimental-jazzy-love-473154/',
    file: 'lofi-sentimental-jazz.mp3',
  },
  {
    id: 'lofi-chill',
    title: 'Lo-fi Chill',
    author: 'AtlasAudio',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/lofi-chill-519566/',
    file: 'lofi-chill.mp3',
  },
  {
    id: 'lofi-hip-hop',
    title: 'Lo-fi Hip-Hop',
    author: 'leberch',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/lofi-lofi-hip-hop-519408/',
    file: 'lofi-hip-hop.mp3',
  },
  {
    id: 'party-dance',
    title: 'Party Dance',
    author: 'prettyjohn1',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/dance-party-dance-526227/',
    file: 'party-dance.mp3',
  },
  {
    id: 'indie-rock-dreamy',
    title: 'Indie Rock Dreamy',
    author: 'alex-morgan',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/rock-indie-rock-dreamy-537459/',
    file: 'indie-rock-dreamy.mp3',
  },
  {
    id: 'cafe-jazz',
    title: 'Peaceful Cafe Jazz',
    author: 'alex-morgan',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/beats-peaceful-cafe-jazz-relaxing-coffee-shop-541031/',
    file: 'cafe-jazz.mp3',
  },
  {
    id: 'once-in-paris',
    title: 'Once In Paris',
    author: 'Pumpupthemind',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/beats-once-in-paris-168895/',
    file: 'once-in-paris.mp3',
  },
  {
    id: 'split-memories',
    title: 'Cozy Lofi Beat – Split Memories',
    author: 'IdoBerg',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/beats-cozy-lofi-beat-split-memmories-248205/',
    file: 'split-memories.mp3',
  },
  {
    id: 'sunset-stars',
    title: 'Cozy Lofi Beat – Sunset Stars',
    author: 'IdoBerg',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/beats-cozy-lofi-beat-sunset-stars-253833/',
    file: 'sunset-stars.mp3',
  },
  {
    id: 'frosty-shadow-of-winter',
    title: 'Frosty Shadow of Winter',
    author: 'ShidenBeatsMusic',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/beats-lo-fi-chill-beat-frosty-shadow-of-winter-136165/',
    file: 'frosty-shadow-of-winter.mp3',
  },
  {
    id: 'lofi-jazz-hip-hop',
    title: 'Lofi Jazz Hip Hop',
    author: 'VibeHorn',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/lofi-lofi-jazz-hip-hop-479218/',
    file: 'lofi-jazz-hip-hop.mp3',
  },
  {
    id: 'lofi-jazz-music',
    title: 'Lofi Jazz Music',
    author: 'lofidreams',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/lofi-lofi-jazz-music-485312/',
    file: 'lofi-jazz-music.mp3',
  },
  {
    id: 'lofi-cafe',
    title: 'Lofi Cafe',
    author: 'lofidreams',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/beats-lofi-cafe-427593/',
    file: 'lofi-cafe.mp3',
  },
  {
    id: 'we-jazz-lofi-soul',
    title: 'WE JAZZ Lofi Soul',
    author: 'jumpingbunny',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/traditional-jazz-we-jazz-lofi-soul-363084/',
    file: 'we-jazz-lofi-soul.mp3',
  },
  {
    id: 'lofi-chill-audiodollar',
    title: 'Lo-Fi Chill',
    author: 'AudioDollar',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/beats-lo-fi-lo-fi-chill-535316/',
    file: 'lofi-chill-audiodollar.mp3',
  },
  {
    id: 'chillhop-remain',
    title: 'Chillhop — Remain',
    author: 'Ornave',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/beats-chillhop-remain-594997/',
    file: 'chillhop-remain.mp3',
  },
  {
    id: 'dreamy-fall-people',
    title: 'Dreamy Fall People',
    author: 'Diamond_Tunes',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/beats-dreamy-fall-people-lo-fi-chill-vlog-179957/',
    file: 'dreamy-fall-people.mp3',
  },
  {
    id: 'chillhop-jazz-coffee-shop',
    title: 'Chillhop Jazz Coffee Shop',
    author: 'alex-morgan',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/lofi-chillhop-jazz-coffee-shop-552792/',
    file: 'chillhop-jazz-coffee-shop.mp3',
  },
  {
    id: 'lofi-study',
    title: 'Lofi Study',
    author: 'The_Mountain',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/old-school-hip-hop-lofi-study-576576/',
    file: 'lofi-study.mp3',
  },
  {
    id: 'afterword-zen-lofi',
    title: 'Afterword (Zen Lofi)',
    author: 'Turning_Pages',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/lofi-afterword-zen-lofi-469291/',
    file: 'afterword-zen-lofi.mp3',
  },
  {
    id: 'chill-hip-hop',
    title: 'Chill Hip Hop Version 2',
    author: 'BombinSound',
    license: 'Pixabay License (free, no attribution required)',
    sourceUrl: 'https://pixabay.com/music/beats-chill-hip-hop-version-2-544088/',
    file: 'chill-hip-hop.mp3',
  },
  {
    id: 'oga-lofi-again',
    title: 'Lofi Again',
    author: 'omfgdude',
    license: 'CC0',
    sourceUrl: 'https://opengameart.org/content/lofi-again',
    file: 'oga-lofi-again.mp3',
  },
  {
    id: 'oga-lofi-loop',
    title: 'Lofi Hip Hop Loop',
    author: 'omfgdude',
    license: 'CC0',
    sourceUrl: 'https://opengameart.org/content/lofi-hip-hop-loop',
    file: 'oga-lofi-loop.mp3',
  },
  {
    id: 'since-2-am',
    title: 'Since 2 A.M.',
    author: 'TAD',
    license: 'CC0',
    sourceUrl: 'https://opengameart.org/content/since-2-am',
    file: 'since-2-am.mp3',
  },
];
