// AUTO-GENERATED by scripts/gen-partials.ts — do not edit.
// Declare a partial by dropping a JSON in src/partials/, then run `pnpm --filter @leclap/creative-kit gen:partials`.
import type { TemplatePartial } from './types';
import flashCard from './partials/flash-card.json';
import logoBumperPortrait from './partials/logo-bumper-portrait.json';
import logoBumper from './partials/logo-bumper.json';

type RawPartial = { sections: TemplatePartial['sections'] };

export const APP_PARTIALS: TemplatePartial[] = [
  {
    id: 'flash-card',
    description:
      "Blinking this-or-that flash card — the two options swap colorA/colorB three times within one section (instant cuts via enable timelines). Every placeholder has a default and is overridable on the ref: optionA/optionB (the two choices), conjunction (separator word, e.g. 'OR' or '&'), and colorA/colorB/textColor (the bold red/white palette).",
    variables: {
      optionA: 'THIS',
      optionB: 'THAT',
      conjunction: 'OR',
      colorA: '#ff2e4d',
      colorB: '#f5f5f0',
      textColor: '#f5f5f0',
    },
    envelope: { in: 0.4, out: 0 },
    syncPoints: [{ id: 'swap', offset: 0.4 }],
    jobs: ['compare', 'ask'],
    useWhen: 'A this-or-that question, poll or A/B choice that should feel loud and playful.',
    avoidWhen: 'Calm, premium or accessibility-sensitive pacing: the colour swap strobes every 0.4 s.',
    sections: (flashCard as RawPartial).sections,
  },
  {
    id: 'logo-bumper-portrait',
    description:
      'LeClap logo sting (portrait): the 2.4 s bumper clip framed by brand-coloured rules, faded in and out.',
    envelope: { in: 0.5, out: 0.5 },
    syncPoints: [{ id: 'logo', offset: 0.5 }],
    jobs: ['brand', 'close'],
    useWhen: 'Open or sign off a video with the LeClap identity, ideally with the logo landing on a downbeat.',
    avoidWhen: 'Mid-video: a bumper reads as a beginning or an ending, never as a transition.',
    sections: (logoBumperPortrait as RawPartial).sections,
  },
  {
    id: 'logo-bumper',
    description:
      'LeClap logo sting (landscape): the 2.4 s bumper clip framed by brand-coloured rules, faded in and out.',
    envelope: { in: 0.5, out: 0.5 },
    syncPoints: [{ id: 'logo', offset: 0.5 }],
    jobs: ['brand', 'close'],
    useWhen: 'Open or sign off a video with the LeClap identity, ideally with the logo landing on a downbeat.',
    avoidWhen: 'Mid-video: a bumper reads as a beginning or an ending, never as a transition.',
    sections: (logoBumper as RawPartial).sections,
  },
];
