// AUTO-GENERATED by scripts/gen-templates.ts — do not edit.
// Add a template JSON under src/templates/ and run `pnpm --dir packages/leclap-creative-kit gen:templates`.
import type { TemplateDescriptor } from './types';
import AppTutorial from './templates/app-tutorial.json';
import FastCurious from './templates/fast-curious.json';
import Interview from './templates/interview.json';
import PhotoBackdrop from './templates/photo-backdrop.json';
import PresentYourselfPortrait from './templates/present-yourself-portrait.json';
import PresentYourself from './templates/present-yourself.json';
import ProductLaunch from './templates/product-launch.json';
import SquarePromo from './templates/square-promo.json';
import StoryReel from './templates/story-reel.json';

export const TEMPLATE_DESCRIPTORS: Record<string, TemplateDescriptor> = {
  'app-tutorial': AppTutorial,
  'fast-curious': FastCurious as TemplateDescriptor,
  interview: Interview as TemplateDescriptor,
  'photo-backdrop': PhotoBackdrop as TemplateDescriptor,
  'present-yourself-portrait': PresentYourselfPortrait as TemplateDescriptor,
  'present-yourself': PresentYourself as TemplateDescriptor,
  'product-launch': ProductLaunch,
  'square-promo': SquarePromo,
  'story-reel': StoryReel as TemplateDescriptor,
};
