// AUTO-GENERATED by scripts/gen-templates.ts — do not edit.
// Add a template JSON under src/templates/ and run `pnpm --dir packages/leclap-creative-kit gen:templates`.
import type { TemplateDescriptor } from './types';
import BigReveal from './templates/big-reveal.json';
import FastCurious from './templates/fast-curious.json';
import Interview from './templates/interview.json';
import PhotoBackdrop from './templates/photo-backdrop.json';
import Spotlight from './templates/spotlight.json';
import SquarePromo from './templates/square-promo.json';
import StoryReel from './templates/story-reel.json';

export const TEMPLATE_DESCRIPTORS: Record<string, TemplateDescriptor> = {
  'big-reveal': BigReveal as TemplateDescriptor,
  'fast-curious': FastCurious as TemplateDescriptor,
  interview: Interview as TemplateDescriptor,
  'photo-backdrop': PhotoBackdrop as TemplateDescriptor,
  spotlight: Spotlight as TemplateDescriptor,
  'square-promo': SquarePromo as TemplateDescriptor,
  'story-reel': StoryReel as TemplateDescriptor,
};
