// GENERATED from scripts/ffmpeg/common.sh — do not edit.
// Regenerate with `pnpm --filter ffmpeg-video-composer generate:capabilities`.
// Freshness is guarded by tests/lgpl-filter-audit.test.ts.

export const DEVICE_FILTERS: ReadonlySet<string> = new Set([
  'acompressor',
  'acrossfade',
  'adelay',
  'aecho',
  'aevalsrc',
  'afade',
  'afftdn',
  'aformat',
  'agate',
  'alimiter',
  'alphamerge',
  'amix',
  'anull',
  'anullsrc',
  'aresample',
  'asetpts',
  'asplit',
  'atempo',
  'atrim',
  'color',
  'colorbalance',
  'colorchannelmixer',
  'colorkey',
  'concat',
  'crop',
  'curves',
  'drawbox',
  'drawtext',
  'dynaudnorm',
  'edgedetect',
  'equalizer',
  'fade',
  'format',
  'fps',
  'gblur',
  'gradients',
  'hflip',
  'highpass',
  'hue',
  'loop',
  'loudnorm',
  'lowpass',
  'lut3d',
  'lutyuv',
  'negate',
  'noise',
  'null',
  'overlay',
  'pad',
  'rgbashift',
  'rotate',
  'scale',
  'setdar',
  'setparams',
  'setpts',
  'setsar',
  'settb',
  'sidechaincompress',
  'sine',
  'split',
  'tile',
  'transpose',
  'trim',
  'vflip',
  'vignette',
  'volume',
  'xfade',
  'zoompan',
]);

/** External libraries the device build links (`--enable-lib<name>`): fribidi = drawtext text_shaping. */
export const DEVICE_LIBRARIES: ReadonlySet<string> = new Set(['freetype', 'fribidi', 'harfbuzz', 'openh264', 'vpx']);
