// Static placeholder clips for the builder's "Preview render": each project_video section is fed a
// pre-rendered, branded "Preview · sample footage" clip (committed under public/videos, generated by
// scripts/render-placeholder.sh in this app) instead of a live canvas/MediaRecorder recording. The recorded
// route produced files FFmpeg-WASM couldn't reliably decode (no output written → "Output file not
// found in WASM"); a bundled MP4 is a known-good input, so the compile path runs exactly as it does
// for a real upload. Mirrors the Expo twin (apps/leclap-expo/.../previewRender.ts), which likewise
// reuses one bundled clip per project_video slot.
import type { EditorState } from '../templateEditorModel';

const PLACEHOLDER_LANDSCAPE = '/videos/placeholder-landscape.mp4';
const PLACEHOLDER_PORTRAIT = '/videos/placeholder-portrait.mp4';

// Fetch the bundled placeholder clip for the template's orientation and hand back `count` copies —
// one File per project_video section, named preview_1…preview_N so the compile service keys them
// positionally to video_1…video_N (storeUploadedFiles). Throws a friendly error if the clip can't
// be loaded so the caller can surface it instead of compiling with no footage.
export async function generatePlaceholderClips(state: EditorState, count: number): Promise<File[]> {
  if (count === 0) return [];

  const src = state.orientation === 'portrait' ? PLACEHOLDER_PORTRAIT : PLACEHOLDER_LANDSCAPE;

  const response = await fetch(src).catch(() => null);

  if (!response || !response.ok) {
    throw new Error('Could not load the preview placeholder clip.');
  }

  const blob = await response.blob();

  return Array.from({ length: count }, (_unused, i) => new File([blob], `preview_${i + 1}.mp4`, { type: 'video/mp4' }));
}
