// AUTO-GENERATED by scripts/copy-core-assets.ts — do not edit.
// Bundled animation overlays for the RN app, keyed by filename → Metro asset id. Re-run the copy step
// (it runs on expo start) after adding a file to the library to refresh this map.
export const ANIMATION_ASSETS: Record<string, number> = {
  'animation_icons.apng': require('../../assets/animations/animation_icons.apng'),
  'confetti.apng': require('../../assets/animations/confetti.apng'),
  'corner_brackets.apng': require('../../assets/animations/corner_brackets.apng'),
  'glow_border.apng': require('../../assets/animations/glow_border.apng'),
  'light_leak.apng': require('../../assets/animations/light_leak.apng'),
  'pulse_ring.apng': require('../../assets/animations/pulse_ring.apng'),
  'rounded_border.apng': require('../../assets/animations/rounded_border.apng'),
  'shine_sweep.apng': require('../../assets/animations/shine_sweep.apng'),
  'sparkle.apng': require('../../assets/animations/sparkle.apng'),
  'white_border.apng': require('../../assets/animations/white_border.apng'),
};
