import { StyleSheet } from 'react-native';
import { colors, spacing, typography, fonts } from '@/src/styles/theme';

export const styles = StyleSheet.create({
  fullscreenContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  videoArea: {
    flex: 1,
    backgroundColor: 'black',
  },
  centerContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xl,
    backgroundColor: colors.background,
  },
  loadingText: {
    ...typography.body,
    marginTop: spacing.m,
  },
  errorText: {
    ...typography.body,
    color: colors.error,
    marginBottom: spacing.l,
    textAlign: 'center',
  },
  backButton: {
    padding: spacing.s,
  },
  backButtonText: {
    ...typography.body,
    color: colors.primary,
  },
  closeButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 2000,
    backgroundColor: 'rgba(255, 255, 255, 0.92)',
    borderRadius: 30,
    width: 56,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 5,
  },
  toolbar: {
    position: 'absolute',
    bottom: 40,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.xl,
    zIndex: 2000,
  },
  toolButton: {
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 64,
    minHeight: 48,
  },
  toolButtonText: {
    color: colors.surface,
    fontFamily: fonts.poppins.semiBold,
    fontSize: 13,
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginTop: spacing.xs,
  },
  editPanel: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(10,8,20,0.92)',
    paddingTop: spacing.l,
    paddingBottom: spacing.xl + spacing.s,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    zIndex: 2000,
  },
  editTitle: {
    color: colors.surface,
    fontFamily: fonts.poppins.semiBold,
    fontSize: 16,
    letterSpacing: 0.5,
    textAlign: 'center',
    marginBottom: spacing.s,
  },
  editActions: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.m,
    paddingHorizontal: spacing.l,
    marginTop: spacing.m,
  },
  ghostButton: {
    paddingVertical: spacing.m,
    paddingHorizontal: spacing.l,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    minHeight: 48,
    justifyContent: 'center',
  },
  ghostButtonText: {
    color: colors.surface,
    fontFamily: fonts.inter.medium,
    fontSize: 15,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: colors.primary,
    paddingVertical: spacing.m,
    paddingHorizontal: spacing.l,
    borderRadius: 14,
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: colors.surface,
    fontFamily: fonts.poppins.semiBold,
    fontSize: 16,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
});
