import { footageUrl } from './media.ts';
import { FRAME, type Background, type Format, type Json, type JsonObject } from './types.ts';

// The fixed stage every effect fixture is rendered on: one section, three backgrounds (mid-grey moving
// footage stand-in, dark card, light card) in three formats, with a "subject" rect the effect can
// target. Fixtures reference the subject geometry through {{tokens}} (see README.md).

/** Subject rect as fractions of the frame (the default target of every fixture). */
export interface SubjectSpec {
  x: number;
  y: number;
  w: number;
  h: number;
  /** Corner radius as a fraction of the subject's short side (0 = square). */
  radius?: number;
}

export const DEFAULT_SUBJECT: SubjectSpec = { x: 0.2, y: 0.24, w: 0.6, h: 0.52, radius: 0 };

const CARD: Record<Exclude<Background, 'footage'>, { bg: string; subject: string }> = {
  dark: { bg: '#121826', subject: '#C9D2E0' },
  light: { bg: '#F0E8DC', subject: '#CDBFA9' },
};

function even(value: number): number {
  return Math.round(value / 2) * 2;
}

/** Pixel geometry and timing tokens for one format. */
export function sceneTokens(format: Format, subject: SubjectSpec, window: { at: number; duration: number }) {
  const { width: W, height: H } = FRAME[format];
  const x = even(W * subject.x);
  const y = even(H * subject.y);
  const w = even(W * subject.w);
  const h = even(H * subject.h);
  const r = even(Math.min(w, h) * (subject.radius ?? 0));
  const side = Math.min(w, h);

  return {
    W,
    H,
    x,
    y,
    w,
    h,
    r,
    cx: even(x + w / 2),
    cy: even(y + h / 2),
    short: side,
    position: `${x}:${y}`,
    scale: `${w}:${h}`,
    squarePosition: `${even(x + (w - side) / 2)}:${even(y + (h - side) / 2)}`,
    squareScale: `${side}:${side}`,
    frameScale: `${W}:${H}`,
    target: { x, y, w, h, radius: r },
    at: window.at,
    duration: window.duration,
    end: window.at + window.duration,
  } satisfies Record<string, Json>;
}

export type Tokens = ReturnType<typeof sceneTokens>;

const TOKEN = /\{\{\s*([a-zA-Z]+)\s*\}\}/g;
const WHOLE = /^\{\{\s*([a-zA-Z]+)\s*\}\}$/;

function tokenValue(tokens: Tokens, name: string): Json {
  if (!(name in tokens)) throw new Error(`unknown fixture token {{${name}}}`);

  return tokens[name as keyof Tokens];
}

function spliced(value: Json): string {
  return typeof value === 'object' ? JSON.stringify(value) : String(value);
}

/** Replace {{tokens}}: a string that is exactly one token takes its raw value (number or object). */
export function applyTokens(value: Json, tokens: Tokens): Json {
  if (typeof value === 'string') {
    const whole = WHOLE.exec(value);

    if (whole) return tokenValue(tokens, whole[1]);

    return value.replace(TOKEN, (_match, name: string) => spliced(tokenValue(tokens, name)));
  }

  if (Array.isArray(value)) return value.map((item) => applyTokens(item, tokens));

  if (value === null || typeof value !== 'object') return value;

  return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, applyTokens(item, tokens)]));
}

/** The background section (no effect yet) for one background, format and duration. */
export function baseSection(background: Background, format: Format, tokens: Tokens, duration: number): JsonObject {
  if (background === 'footage') {
    return { name: 'review', type: 'video', options: { videoUrl: footageUrl(format), duration } };
  }

  const card = CARD[background];
  const subject = { color: card.subject, x: tokens.x, y: tokens.y, w: tokens.w, h: tokens.h };

  return {
    name: 'review',
    type: 'color_background',
    options: { backgroundColor: card.bg, duration, layers: [subject] },
  };
}

/** A complete one-section descriptor around the base section. */
export function sceneDescriptor(format: Format, section: JsonObject, title: string, global?: JsonObject): JsonObject {
  return {
    meta: { name: title, description: 'Motion review fixture (generated by scripts/motion-review).' },
    global: { orientation: format, musicEnabled: false, seed: 7, transition: { type: 'cut' }, ...global },
    sections: [section],
  };
}
