// Generates, per bundled font and straight from the font files (the compile path can't read them: WASM
// and React Native fetch fonts lazily):
// - src/core/font-advances.generated.ts: the glyph advance widths kinetic typography needs to lay out
//   words and glyphs synchronously on every platform;
// - src/core/font-coverage.generated.ts: every BMP code point the font has a glyph for, as ranges, so
//   validation can name the characters a font would draw as empty boxes.
// Run with `pnpm generate:font-advances`; tests/kinetic.test.ts and tests/glyph-coverage.test.ts fail
// when a table drifts from the fonts.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { FONTS } from '../src/core/fonts';
import { parseFontMetrics, type FontMetrics } from '../src/core/font-metrics';
import { encodeRanges } from '../src/core/font-coverage';

const here = path.dirname(fileURLToPath(import.meta.url));
const fontsDir = path.resolve(here, '../../leclap-creative-kit/src/library/fonts');
const outPath = path.resolve(here, '../src/core/font-advances.generated.ts');
const coverageOutPath = path.resolve(here, '../src/core/font-coverage.generated.ts');

// Basic Latin, Latin-1 Supplement and Latin Extended-A: Western and Central European copy.
export const FIRST_CODE_POINT = 0x20;
export const LAST_CODE_POINT = 0x17f;

// The cmap reader handles format 4, i.e. the BMP — all a bundled face maps.
const LAST_BMP_CODE_POINT = 0xffff;

function readMetrics(file: string): FontMetrics {
  const metrics = parseFontMetrics(new Uint8Array(fs.readFileSync(path.join(fontsDir, file))));

  if (!metrics) throw new Error(`cannot parse ${file}`);

  return metrics;
}

/** Advance widths per bundled font file, straight from the font files. */
export function buildFontAdvances(): Record<string, { unitsPerEm: number; advances: number[] }> {
  return Object.fromEntries(
    FONTS.map((font) => {
      const metrics = readMetrics(font.file);
      const advances: number[] = [];

      for (let cp = FIRST_CODE_POINT; cp <= LAST_CODE_POINT; cp++) advances.push(metrics.advanceWidth(cp) ?? -1);

      return [font.file, { unitsPerEm: metrics.unitsPerEm, advances }];
    })
  );
}

export function buildFontAdvancesSource(): string {
  const entries = Object.entries(buildFontAdvances()).map(
    ([file, table]) => `  '${file}': { unitsPerEm: ${table.unitsPerEm}, advances: [${table.advances.join(',')}] },`
  );

  return [
    '// GENERATED by scripts/generate-font-advances.ts from the bundled fonts — do not edit.',
    '// Advance widths in font units for code points FIRST..LAST; -1 = the font has no glyph.',
    '',
    `export const FIRST_CODE_POINT = ${FIRST_CODE_POINT};`,
    `export const LAST_CODE_POINT = ${LAST_CODE_POINT};`,
    '',
    'export const FONT_ADVANCES: Readonly<Record<string, { unitsPerEm: number; advances: readonly number[] }>> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

// Inclusive [start, end] pairs, flattened, of the printable code points the font maps to a glyph.
function coveredRanges(metrics: FontMetrics): number[] {
  const ranges: number[] = [];
  let start = -1;

  for (let cp = FIRST_CODE_POINT; cp <= LAST_BMP_CODE_POINT + 1; cp++) {
    const covered = cp <= LAST_BMP_CODE_POINT && metrics.advanceWidth(cp) !== null;

    if (covered && start < 0) start = cp;

    if (!covered && start >= 0) {
      ranges.push(start, cp - 1);
      start = -1;
    }
  }

  return ranges;
}

/** Covered code-point ranges per bundled font file, encoded (see encodeRanges). */
export function buildFontCoverage(): Record<string, string> {
  return Object.fromEntries(FONTS.map((font) => [font.file, encodeRanges(coveredRanges(readMetrics(font.file)))]));
}

export function buildFontCoverageSource(): string {
  const entries = Object.entries(buildFontCoverage()).map(([file, ranges]) => `  '${file}': '${ranges}',`);

  return [
    '// GENERATED by scripts/generate-font-advances.ts from the bundled fonts — do not edit.',
    '// Per font, the code points it has a glyph for, as ranges encoded by encodeRanges (font-coverage.ts).',
    '',
    'export const FONT_COVERAGE: Readonly<Record<string, string>> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(outPath, buildFontAdvancesSource());
  fs.writeFileSync(coverageOutPath, buildFontCoverageSource());
  console.log(`wrote ${outPath} and ${coverageOutPath}`);
}
