// Generates src/core/font-advances.generated.ts: per bundled font, the glyph advance widths kinetic
// typography needs to lay out words and glyphs synchronously on every platform (the compile path can't
// read font files: WASM and React Native fetch them lazily). Run with `pnpm generate:font-advances`;
// tests/kinetic-layout.test.ts fails when the table drifts from the fonts.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { FONTS } from '../src/core/fonts';
import { parseFontMetrics } from '../src/core/font-metrics';

const here = path.dirname(fileURLToPath(import.meta.url));
const fontsDir = path.resolve(here, '../../leclap-creative-kit/src/library/fonts');
const outPath = path.resolve(here, '../src/core/font-advances.generated.ts');

// Basic Latin, Latin-1 Supplement and Latin Extended-A: Western and Central European copy.
export const FIRST_CODE_POINT = 0x20;
export const LAST_CODE_POINT = 0x17f;

/** Advance widths per bundled font file, straight from the font files. */
export function buildFontAdvances(): Record<string, { unitsPerEm: number; advances: number[] }> {
  return Object.fromEntries(
    FONTS.map((font) => {
      const metrics = parseFontMetrics(new Uint8Array(fs.readFileSync(path.join(fontsDir, font.file))));

      if (!metrics) throw new Error(`cannot parse ${font.file}`);

      const advances: number[] = [];

      for (let cp = FIRST_CODE_POINT; cp <= LAST_CODE_POINT; cp++) advances.push(metrics.advanceWidth(cp) ?? -1);

      return [font.file, { unitsPerEm: metrics.unitsPerEm, advances }];
    })
  );
}

export function buildFontAdvancesSource(): string {
  const entries = Object.entries(buildFontAdvances()).map(
    ([file, table]) => `  '${file}': { unitsPerEm: ${table.unitsPerEm}, advances: [${table.advances.join(',')}] },`
  );

  return [
    '// GENERATED by scripts/generate-font-advances.ts from the bundled fonts — do not edit.',
    '// Advance widths in font units for code points FIRST..LAST; -1 = the font has no glyph.',
    '',
    `export const FIRST_CODE_POINT = ${FIRST_CODE_POINT};`,
    `export const LAST_CODE_POINT = ${LAST_CODE_POINT};`,
    '',
    'export const FONT_ADVANCES: Readonly<Record<string, { unitsPerEm: number; advances: readonly number[] }>> = {',
    ...entries,
    '};',
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(outPath, buildFontAdvancesSource());
  console.log(`wrote ${outPath}`);
}
