import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '@/src/styles/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.m,
    paddingVertical: spacing.s,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
    backgroundColor: colors.surface,
  },
  backButton: {
    padding: spacing.s,
  },
  headerTitle: {
    ...typography.title,
    flex: 1,
    textAlign: 'center',
  },
  selectAllButton: {
    padding: spacing.s,
  },
  selectAllText: {
    ...typography.caption,
    color: colors.primary,
    fontWeight: '500',
  },
  summaryBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s,
    backgroundColor: colors.primary + '12',
    marginHorizontal: spacing.m,
    marginTop: spacing.s,
    paddingHorizontal: spacing.m,
    paddingVertical: spacing.s,
    borderRadius: 12,
  },
  summaryText: {
    ...typography.caption,
    color: colors.primaryDark,
    fontWeight: '600',
  },
  actionBar: {
    flexDirection: 'row',
    paddingHorizontal: spacing.m,
    paddingVertical: spacing.s,
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
    gap: spacing.s,
  },
  actionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.background,
    paddingHorizontal: spacing.m,
    paddingVertical: spacing.s,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.divider,
    gap: spacing.xs,
  },
  actionButtonDisabled: {
    opacity: 0.5,
  },
  actionButtonText: {
    ...typography.caption,
    fontWeight: '500',
  },
  filterContainer: {
    backgroundColor: colors.surface,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  filterContent: {
    paddingHorizontal: spacing.m,
    paddingVertical: spacing.s,
    gap: spacing.s,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.m,
    paddingVertical: spacing.s,
    borderRadius: 20,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.divider,
    gap: spacing.xs,
  },
  filterButtonActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterButtonText: {
    ...typography.caption,
    fontWeight: '500',
    color: colors.text,
  },
  filterButtonTextActive: {
    color: 'white',
  },
  filterBadge: {
    backgroundColor: colors.warning,
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterBadgeText: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
  },
  listContainer: {
    flex: 1,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.xxl,
  },
  emptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.primary + '12',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.m,
  },
  emptyTitle: {
    ...typography.subtitle,
    color: colors.text,
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  emptyText: {
    ...typography.caption,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 20,
  },
  emptyCta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.l,
    paddingVertical: spacing.s + 2,
    borderRadius: 24,
    marginTop: spacing.l,
    shadowColor: colors.primary,
    shadowOpacity: 0.3,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  emptyCtaText: {
    ...typography.button,
    color: colors.surface,
  },
  emptyCtaGhost: {
    paddingHorizontal: spacing.l,
    paddingVertical: spacing.s,
    borderRadius: 24,
    marginTop: spacing.m,
  },
  emptyCtaGhostText: {
    ...typography.button,
    fontSize: 14,
    color: colors.primary,
  },
  queueItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.m,
    backgroundColor: colors.surface,
    marginHorizontal: spacing.m,
    marginVertical: spacing.xs,
    paddingVertical: spacing.m,
    paddingRight: spacing.m,
    paddingLeft: spacing.m + 4, // clears the accent bar
    borderRadius: 16,
    // Soft, low-contrast shadow (Soft-UI) — no harsh borders.
    shadowColor: colors.text,
    shadowOpacity: 0.06,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
    overflow: 'hidden',
  },
  queueItemSelected: {
    backgroundColor: colors.primary + '0D',
  },
  accentBar: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 4,
  },
  thumb: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: colors.primary + '14',
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectionIndicator: {
    marginLeft: spacing.xs,
  },
  queueItemInfo: {
    flex: 1,
    gap: spacing.xs,
  },
  queueItemTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.s,
  },
  queueItemTitle: {
    ...typography.body,
    fontWeight: '600',
    flexShrink: 1,
  },
  queueItemTime: {
    ...typography.smallText,
    color: colors.textSecondary,
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s,
  },
  statusPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    paddingHorizontal: spacing.s,
    paddingVertical: 3,
    borderRadius: 999,
  },
  statusPillText: {
    ...typography.smallText,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  retryCount: {
    ...typography.smallText,
    color: colors.warning,
  },
  errorText: {
    ...typography.smallText,
    color: colors.error,
  },
  batchModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  batchModalContent: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: spacing.l,
    paddingBottom: spacing.xl,
  },
  batchModalTitle: {
    ...typography.subtitle,
    textAlign: 'center',
    marginBottom: spacing.l,
  },
  batchActions: {
    flexDirection: 'row',
    gap: spacing.m,
    marginBottom: spacing.l,
  },
  batchButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.m,
    borderRadius: 12,
    gap: spacing.s,
  },
  batchRetryButton: {
    backgroundColor: colors.primary + '15',
    borderWidth: 1,
    borderColor: colors.primary + '30',
  },
  batchRemoveButton: {
    backgroundColor: colors.error + '10',
    borderWidth: 1,
    borderColor: colors.error + '20',
  },
  batchButtonText: {
    ...typography.body,
    fontWeight: '600',
  },
  batchCancelButton: {
    alignItems: 'center',
    paddingVertical: spacing.m,
  },
  batchCancelText: {
    ...typography.body,
    color: colors.textSecondary,
  },
});
