#!/usr/bin/env node
// Generate src/partials.generated.ts from every src/partials/*.json, so a partial is "declared" by
// just dropping a JSON file in src/partials/ (its id is the filename) — no hand-edited registry.
// The output uses static imports so it bundles everywhere (Vite, Metro, tsdown). Each JSON may
// carry an optional top-level "description"; the id defaults to the filename.
//
//   pnpm --filter @leclap/creative-kit gen:partials
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const partialsDir = path.resolve(here, '../src/partials');
const outFile = path.resolve(here, '../src/partials.generated.ts');

const toCamel = (id: string) => id.replace(/[-_](.)/g, (_, c: string) => c.toUpperCase());
const META_KEYS = ['envelope', 'syncPoints', 'jobs', 'useWhen', 'avoidWhen'];

const entries = readdirSync(partialsDir)
  .filter((f) => f.endsWith('.json'))
  .sort()
  .map((file) => {
    const id = file.replace(/\.json$/, '');
    const json = JSON.parse(readFileSync(path.join(partialsDir, file), 'utf8')) as Record<string, unknown>;

    const variables = json.variables && typeof json.variables === 'object' ? json.variables : undefined;
    // Timing and catalog metadata (envelope, sync points, rhetorical jobs, when to use / avoid) travel
    // with the registry so editors and agents can choose and re-time a partial without loading it.
    const meta = Object.fromEntries(META_KEYS.flatMap((key) => (json[key] === undefined ? [] : [[key, json[key]]])));

    return {
      id,
      varName: toCamel(id),
      description: typeof json.description === 'string' ? json.description : id,
      variables,
      meta,
    };
  });

const imports = entries.map((e) => `import ${e.varName} from './partials/${e.id}.json';`).join('\n');
const rows = entries
  .map((e) => {
    const vars = e.variables ? `variables: ${JSON.stringify(e.variables)}, ` : '';
    const meta = Object.entries(e.meta)
      .map(([key, value]) => `${key}: ${JSON.stringify(value)}, `)
      .join('');

    return `  { id: ${JSON.stringify(e.id)}, description: ${JSON.stringify(e.description)}, ${vars}${meta}sections: (${e.varName} as RawPartial).sections },`;
  })
  .join('\n');

const content = `// AUTO-GENERATED by scripts/gen-partials.ts — do not edit.
// Declare a partial by dropping a JSON in src/partials/, then run \`pnpm --filter @leclap/creative-kit gen:partials\`.
import type { TemplatePartial } from './types';
${imports}

type RawPartial = { sections: TemplatePartial['sections'] };

export const APP_PARTIALS: TemplatePartial[] = [
${rows}
];
`;

writeFileSync(outFile, content);
console.log(
  `Wrote ${path.relative(process.cwd(), outFile)} — ${entries.length} partials: ${entries.map((e) => e.id).join(', ')}`
);
