#!/usr/bin/env node
// Generate src/templates.generated.ts from every src/templates/*.json template. Bundlers need
// static imports, so runtime directory walking is not portable to Vite/Metro/tsdown.
import { readdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const srcDir = path.resolve(here, '../src');
const templatesDir = path.join(srcDir, 'templates');
const outFile = path.join(srcDir, 'templates.generated.ts');

const toVarName = (id: string) => id.replace(/(^|[-_])(\w)/g, (_, __, c: string) => c.toUpperCase());

const entries = readdirSync(templatesDir)
  .filter((file) => file.endsWith('.json'))
  .sort()
  .map((file) => {
    const id = file.replace(/\.json$/, '');

    return { id, file, varName: toVarName(id) };
  });

const imports = entries.map((entry) => `import ${entry.varName} from './templates/${entry.file}';`).join('\n');
const rows = entries
  .map((entry) => `  ${JSON.stringify(entry.id)}: ${entry.varName} as TemplateDescriptor,`)
  .join('\n');

const content = `// AUTO-GENERATED by scripts/gen-templates.ts — do not edit.
// Add a template JSON under src/templates/ and run \`pnpm --dir packages/leclap-creative-kit gen:templates\`.
import type { TemplateDescriptor } from './types';
${imports}

export const TEMPLATE_DESCRIPTORS: Record<string, TemplateDescriptor> = {
${rows}
};
`;

writeFileSync(outFile, content);
console.log(
  `Wrote ${path.relative(process.cwd(), outFile)} — ${entries.length} templates: ${entries.map((entry) => entry.id).join(', ')}`
);
