// The shape registry of the music covers: every ShapeName of music-covers-types.ts mapped to its helper.
import type { Shape } from './music-covers-primitives.ts';
import type { ShapeName } from './music-covers-types.ts';
import { frost, hills, leaves, pines, rain, snow, stars, windowShape } from './music-covers-scenery.ts';
import { awning, confetti, notes, pixelNight, rect, rooftops, skyline, waves } from './music-covers-backdrops.ts';
import {
  armchair,
  bass,
  cup,
  eiffel,
  glow,
  headphones,
  lamp,
  moonShape,
  mug,
  pianoKeys,
  plant,
  sun,
  table,
  trumpet,
  turntable,
  vinyl,
} from './music-covers-props-a.ts';
import {
  boombox,
  cassette,
  clouds,
  duck,
  elevator,
  grandPiano,
  guitar,
  infinity,
  kite,
  leaf,
  loopArrows,
  neonCup,
  notebook,
  pencil,
  ripples,
  stones,
} from './music-covers-props-b.ts';
import { banana, cat, cocktail, crane, discoBall, palm, rose, swirl, target, tree } from './music-covers-props-c.ts';

export const SHAPES: Record<ShapeName, Shape> = {
  armchair,
  awning,
  banana,
  bass,
  boombox,
  cassette,
  cat,
  clouds,
  cocktail,
  confetti,
  crane,
  cup,
  discoBall,
  duck,
  eiffel,
  elevator,
  frost,
  glow,
  grandPiano,
  guitar,
  headphones,
  hills,
  infinity,
  kite,
  lamp,
  leaf,
  leaves,
  loopArrows,
  moon: moonShape,
  mug,
  neonCup,
  notebook,
  notes,
  palm,
  pencil,
  pianoKeys,
  pines,
  pixelNight,
  plant,
  rain,
  rect,
  ripples,
  rooftops,
  rose,
  skyline,
  snow,
  stars,
  stones,
  sun,
  swirl,
  table,
  target,
  tree,
  trumpet,
  turntable,
  vinyl,
  waves,
  window: windowShape,
};

// Shapes drawn in canvas coordinates; every other shape is drawn around its origin and placed by x/y/s/rot.
export const ABSOLUTE = new Set<ShapeName>([
  'awning',
  'confetti',
  'frost',
  'hills',
  'leaves',
  'notes',
  'pines',
  'pixelNight',
  'rain',
  'rect',
  'rooftops',
  'skyline',
  'snow',
  'stars',
  'waves',
  'window',
]);
