import 'reflect-metadata';
import { execFile, execFileSync } from 'node:child_process';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';

import type { McpConfig } from '../src/config.js';
import { analysisResult, type MusicAnalyzer, registerAnalyzeMusic } from '../src/tools/analyzeMusic.js';

const execFileAsync = promisify(execFile);

type Handler = (args: Record<string, unknown>) => Promise<{
  isError?: boolean;
  content: Array<{ text: string }>;
  structuredContent?: Record<string, unknown>;
}>;

function captureHandler(cfg: McpConfig, analyzer?: MusicAnalyzer): { name: string; handler: Handler } {
  let captured: { name: string; handler: Handler } | undefined;
  const fakeServer = {
    registerTool: (name: string, _meta: unknown, cb: Handler) => {
      captured = { name, handler: cb };
    },
  };

  registerAnalyzeMusic(fakeServer as never, cfg, analyzer);

  if (!captured) throw new Error('handler was not registered');

  return captured;
}

const ANALYSIS = {
  bpm: 128,
  offset: 0.37,
  beatsPerBar: 4,
  times: [0.37, 0.839, 1.307],
  confidence: 4.9,
  usable: true,
  cues: { build: 8, drop: 15.37, end: 30 },
};

let mediaDir: string;
let outsideDir: string;
let config: McpConfig;

beforeEach(async () => {
  mediaDir = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), 'leclap-music-')));
  outsideDir = await fs.realpath(await fs.mkdtemp(path.join(os.tmpdir(), 'leclap-outside-')));
  config = { outputDir: mediaDir, mediaDir, renderTimeoutMs: 1000, allowRemotion: false };
});

afterEach(async () => {
  await fs.rm(mediaDir, { recursive: true, force: true });
  await fs.rm(outsideDir, { recursive: true, force: true });
});

const neverAnalyzer: MusicAnalyzer = async () => {
  throw new Error('analyzer must not run when the path is rejected');
};

describe('analyze_music', () => {
  it('registers under its published name', () => {
    expect(captureHandler(config, neverAnalyzer).name).toBe('analyze_music');
  });

  it('rejects a file outside the media dir before decoding anything', async () => {
    const outside = path.join(outsideDir, 'track.mp3');
    await fs.writeFile(outside, 'x');

    const result = await captureHandler(config, neverAnalyzer).handler({ path: outside });

    expect(result.isError).toBe(true);
    expect(result.content[0].text).toMatch(/escapes the media directory/);
  });

  it('maps an analysis to the grid a template takes', async () => {
    const track = path.join(mediaDir, 'track.mp3');
    await fs.writeFile(track, 'x');
    let received: { beatsPerBar?: number } | undefined;
    const analyzer: MusicAnalyzer = async (_file, options) => {
      received = options;

      return ANALYSIS;
    };

    const result = await captureHandler(config, analyzer).handler({ path: track, beatsPerBar: 3 });

    expect(received?.beatsPerBar).toBe(3);
    expect(result.structuredContent).toMatchObject({
      bpm: 128,
      offset: 0.37,
      beatCount: 3,
      cues: { drop: 15.37 },
      globalBeats: { bpm: 128, offset: 0.37, beatsPerBar: 4, confidence: 4.9, usable: true },
    });
    expect(result.structuredContent?.times).toBeUndefined();
    expect(result.structuredContent?.advice).toMatch(/15\.37s/);
  });

  it('tells the agent to pace by phrases when the pulse is unreliable', () => {
    const calm = analysisResult({ ...ANALYSIS, usable: false, confidence: 1.2 }, true);

    expect(calm.advice).toMatch(/pace by phrases/);
    expect(calm.times).toEqual(ANALYSIS.times);
  });

  it('reports a decode failure as a tool error', async () => {
    const track = path.join(mediaDir, 'broken.mp3');
    await fs.writeFile(track, 'not audio');
    const result = await captureHandler(config, async () => {
      throw new Error('could not decode');
    }).handler({ path: track });

    expect(result.isError).toBe(true);
    expect(result.content[0].text).toMatch(/Analysis failed: could not decode/);
  });
});

function hasFfmpeg(): boolean {
  try {
    execFileSync('ffmpeg', ['-version'], { stdio: 'ignore' });

    return true;
  } catch {
    return false;
  }
}

describe.skipIf(!hasFfmpeg())('analyze_music on a real file', () => {
  it('measures a 120 BPM click track generated by FFmpeg', async () => {
    const track = path.join(mediaDir, 'clicks.wav');

    // A 10 ms 1 kHz click every 0.5 s, starting at 0.25 s.
    await execFileAsync('ffmpeg', [
      '-v',
      'error',
      '-f',
      'lavfi',
      '-i',
      "aevalsrc='if(lt(mod(t-0.25+10,0.5),0.01),0.8*sin(2*PI*1000*t),0)':s=22050:d=12",
      track,
    ]);

    const result = await captureHandler(config).handler({ path: track });
    const content = result.structuredContent as { bpm: number; offset: number; usable: boolean };

    expect(result.isError).toBeUndefined();
    expect(content.bpm).toBeCloseTo(120, 0);
    expect(Math.abs(content.offset - 0.25)).toBeLessThan(0.02);
    expect(content.usable).toBe(true);
  }, 30_000);
});
