import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

// Codegen: inline every built-in template JSON from the CORE SOURCE into a checked-in
// TypeScript module. The core ships only `dist` in its npm tarball, so the templates would not
// be reachable at runtime — embedding them at build time keeps the catalog self-contained.
// Run via `pnpm embed-templates`; commit the generated file (it must be tracked, not ignored).
const here = path.dirname(fileURLToPath(import.meta.url));
const coreRoot = path.resolve(here, '../../ffmpeg-video-composer');
const outFile = path.resolve(here, '../src/catalog/templates.generated.ts');

// The catalog ships ONLY the curated app templates (src/shared/templates) — the same premium set
// the web + expo apps expose. Test/scenario fixtures (tests/fixtures) are intentionally excluded:
// they are engine test inputs, not user-facing starting points. Ids stay the filename.
const TEMPLATE_DIRS = [path.join(coreRoot, 'src/shared/templates')];

function buildEntries(): string {
  const files = TEMPLATE_DIRS.flatMap((dir) =>
    fs
      .readdirSync(dir)
      .filter((name) => name.endsWith('.json'))
      .map((name) => path.join(dir, name))
  ).sort((a, b) => path.basename(a).localeCompare(path.basename(b)));

  return files
    .map((file) => {
      const id = path.basename(file, '.json');
      const raw = fs.readFileSync(file, 'utf8');
      const pretty = JSON.stringify(JSON.parse(raw), null, 2);

      return `  ${JSON.stringify(id)}: ${pretty} as TemplateDescriptor,`;
    })
    .join('\n');
}

const header = '// AUTO-GENERATED by scripts/embedTemplates.ts — do not edit by hand. Run `pnpm embed-templates`.';

const content = `${header}
import type { TemplateDescriptor } from 'ffmpeg-video-composer';

export const builtinTemplates: Record<string, TemplateDescriptor> = {
${buildEntries()}
};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, content);

// Run the repo formatter (oxfmt via vp) over the freshly written file so the checked-in output
// is byte-identical to what the pre-commit `vp staged` hook would produce — otherwise the hook
// would rewrite it and re-running this script would never be idempotent.
execFileSync('vp', ['fmt', '--write', outFile], { stdio: 'inherit' });

process.stdout.write(`[embed-templates] wrote ${path.relative(process.cwd(), outFile)}\n`);
