// AUTO-GENERATED by scripts/gen-partials.mjs — do not edit.
// Declare a partial by dropping a JSON in src/partials/, then run `pnpm --filter @leclap/creative-kit gen:partials`.
import type { TemplatePartial } from './partials';
import flashCard from './partials/flash-card.json';
import logoBumper from './partials/logo-bumper.json';

type RawPartial = { sections: TemplatePartial['sections'] };

export const APP_PARTIALS: TemplatePartial[] = [
  {
    id: 'flash-card',
    description:
      "Blinking this-or-that flash card — the two options swap colorA/colorB three times within one section (instant cuts via enable timelines). Every placeholder has a default and is overridable on the ref: optionA/optionB (the two choices), index (progress number), conjunction (separator word, e.g. 'OR' or '&'), showLabel ('1'/'0' to show/hide the 'PICK ONE — n / 3' label box), and colorA/colorB/textColor (the bold red/white palette).",
    variables: {
      optionA: 'THIS',
      optionB: 'THAT',
      index: '1',
      conjunction: 'OR',
      showLabel: '1',
      colorA: '#ff2e4d',
      colorB: '#f5f5f0',
      textColor: '#f5f5f0',
    },
    sections: (flashCard as RawPartial).sections,
  },
  { id: 'logo-bumper', description: 'logo-bumper', sections: (logoBumper as RawPartial).sections },
];
