// AUTO-GENERATED by scripts/gen-templates.mjs — do not edit.
// Add a template JSON under src/templates/ and run `pnpm --dir packages/creative-kit gen:templates`.
import type { TemplateDescriptor } from './types';
import FastCurious from './templates/fast-curious.json';
import Intro from './templates/intro.json';
import LandscapeSpotlight from './templates/landscape-spotlight.json';
import PortraitSpotlight from './templates/portrait-spotlight.json';

export const TEMPLATE_DESCRIPTORS: Record<string, TemplateDescriptor> = {
  'fast-curious': FastCurious as TemplateDescriptor,
  intro: Intro as TemplateDescriptor,
  'landscape-spotlight': LandscapeSpotlight as TemplateDescriptor,
  'portrait-spotlight': PortraitSpotlight as TemplateDescriptor,
};
