import { StyleSheet } from 'react-native';
import { colors, spacing, typography, fonts } from '@/src/styles/theme';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: spacing.xl },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.m,
    paddingVertical: spacing.s,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  backButton: { padding: spacing.s, marginRight: spacing.s },
  title: { ...typography.title, flex: 1 },
  content: { flex: 1, paddingHorizontal: spacing.m },
  contentContainer: { paddingTop: spacing.l, paddingBottom: spacing.xxl + 30 },
  orientationRow: { flexDirection: 'row', alignItems: 'center', marginTop: spacing.s },
  orientationText: { ...typography.body, marginLeft: spacing.s },
  description: { ...typography.body, marginTop: spacing.m, marginBottom: spacing.m },
  progressBarContainer: {
    height: 8,
    backgroundColor: colors.divider,
    borderRadius: 4,
    overflow: 'hidden',
    marginTop: spacing.m,
  },
  progressBar: { height: '100%', backgroundColor: colors.success, borderRadius: 4 },
  progressText: {
    ...typography.caption,
    textAlign: 'center',
    marginTop: spacing.s,
    color: colors.textSecondary,
    marginBottom: spacing.m,
  },
  sectionTitle: { ...typography.subtitle, marginTop: spacing.m, marginBottom: spacing.m },
  sectionItem: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    marginBottom: spacing.m,
    borderWidth: 1,
    borderColor: colors.divider,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  sectionItemContent: { flexDirection: 'row', alignItems: 'center', padding: spacing.m },
  sectionTypeIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary + '10',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.m,
  },
  sectionItemText: { flex: 1 },
  sectionItemTitle: { ...typography.subtitle, marginBottom: spacing.xs },
  sectionItemDescription: { ...typography.caption },
  sectionItemStatus: { marginLeft: spacing.m },
  sectionItemActions: { borderTopWidth: 1, borderTopColor: colors.divider, padding: spacing.s, alignItems: 'center' },
  previewButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.m,
    paddingVertical: spacing.xs,
    borderRadius: 4,
    backgroundColor: colors.primary + '10',
  },
  previewButtonText: { ...typography.caption, color: colors.primary, marginLeft: spacing.xs, fontWeight: '500' },
  footer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: spacing.m,
    paddingBottom: spacing.l,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
    backgroundColor: colors.background,
  },
  createButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingVertical: spacing.m,
    paddingHorizontal: spacing.m,
    borderRadius: 16,
    minHeight: 56,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 6,
  },
  disabledButton: { opacity: 0.45 },
  createButtonText: {
    color: 'white',
    fontFamily: fonts.poppins.semiBold,
    fontSize: 18,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  loader: { marginLeft: spacing.m },
  loadingText: { ...typography.body, marginTop: spacing.m },
  errorText: { ...typography.body, color: colors.error, marginBottom: spacing.l },
  backButtonText: { ...typography.body, color: colors.primary },
  formModalContainer: { flex: 1, backgroundColor: colors.background },
  formHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.m,
    borderBottomWidth: 1,
    borderBottomColor: colors.divider,
  },
  formTitle: { ...typography.title, flex: 1, marginRight: spacing.m },
  formFooter: {
    padding: spacing.m,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
    backgroundColor: colors.surface,
  },
  formSubmitButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.m,
    borderRadius: 14,
    alignItems: 'center',
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 4,
  },
  formSubmitButtonText: {
    color: 'white',
    fontFamily: fonts.poppins.semiBold,
    fontSize: 17,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  modeToggle: {
    flexDirection: 'row',
    backgroundColor: colors.divider,
    borderRadius: 12,
    padding: 3,
    marginTop: spacing.s,
    marginBottom: spacing.s,
  },
  modeToggleOption: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: spacing.xs + 2,
    borderRadius: 10,
  },
  modeToggleOptionActive: {
    backgroundColor: colors.surface,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.12,
    shadowRadius: 6,
    elevation: 2,
  },
  modeToggleText: { ...typography.caption, marginLeft: spacing.xs, color: colors.textSecondary, fontWeight: '500' },
  modeToggleTextActive: { color: colors.text },
  stepIndicator: { ...typography.caption, color: colors.primary, fontWeight: '600', marginTop: spacing.m },
  stepTitle: { ...typography.title, marginTop: spacing.xs, marginBottom: spacing.s },
  stepDescription: { ...typography.body, color: colors.textSecondary, marginBottom: spacing.l },
  stepStatusRow: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.l },
  stepStatusText: { ...typography.body, marginLeft: spacing.s },
  stepPrimaryButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.primary,
    paddingVertical: spacing.m,
    borderRadius: 16,
    minHeight: 56,
    marginTop: spacing.s,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 6,
  },
  stepPrimaryButtonText: {
    color: 'white',
    fontFamily: fonts.poppins.semiBold,
    fontSize: 18,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  stepNav: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.m,
    paddingBottom: spacing.l,
    borderTopWidth: 1,
    borderTopColor: colors.divider,
    backgroundColor: colors.background,
  },
  stepNavButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.s,
    paddingHorizontal: spacing.m,
    borderRadius: 12,
  },
  stepNavButtonPrimary: { backgroundColor: colors.primary },
  stepNavButtonDisabled: { opacity: 0.4 },
  stepNavText: { ...typography.button, color: colors.primary, marginHorizontal: spacing.xs },
  stepNavTextPrimary: { color: 'white' },
  placeholderContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: spacing.l },
  placeholderText: { ...typography.body, marginVertical: spacing.m, textAlign: 'center' },
  tempCompleteButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.l,
    paddingVertical: spacing.m,
    borderRadius: 8,
    marginTop: spacing.l,
  },
  tempCompleteButtonText: { color: colors.surface, fontWeight: 'bold' },
  musicScroll: { padding: spacing.l },
  musicHint: { ...typography.caption, color: colors.textSecondary, marginBottom: spacing.m },
  musicDefaultRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s,
    minHeight: 56,
    paddingHorizontal: spacing.m,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.divider,
    backgroundColor: colors.surface,
    marginBottom: spacing.s,
  },
  musicDefaultRowActive: { borderColor: colors.primary, backgroundColor: 'rgba(124,131,253,0.06)' },
  musicDefaultText: { ...typography.body, color: colors.text, flex: 1 },
  musicTrackRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.s,
    minHeight: 56,
    paddingHorizontal: spacing.m,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.divider,
    backgroundColor: colors.surface,
    marginBottom: spacing.s,
  },
  musicTrackRowActive: { borderColor: colors.primary, backgroundColor: 'rgba(124,131,253,0.06)' },
  musicTrackText: { flex: 1 },
  musicTrackTitle: { ...typography.body, color: colors.text },
  musicTrackAuthor: { ...typography.smallText, color: colors.textSecondary },
});
