// AUTO-GENERATED by scripts/embedTemplates.ts — do not edit by hand. Run `pnpm embed-templates`.
import type { TemplateDescriptor } from 'ffmpeg-video-composer';

export const builtinTemplates: Record<string, TemplateDescriptor> = {
  concat_videos_with_music: {
    global: {
      variables: {
        video: 'https://github.com/heristop/ffmpeg-video-composer/raw/main/src/shared/assets/videos/earth.mp4',
        colorTransition: '#000000',
      },
      music: {
        name: 'point_being_-_go_by_ocean___ryan_mccaffrey.mp3',
      },
      orientation: 'landscape',
      musicEnabled: true,
      transitionDuration: 0.1,
    },
    sections: [
      {
        name: 'test_video_1',
        type: 'video',
        options: {
          videoUrl: '{{ video }}',
          duration: 4,
          musicVolumeLevel: 1,
        },
        filters: [
          {
            type: 'fadein',
            values: {
              color: '{{ colorTransition }}',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '{{ colorTransition }}',
            },
          },
        ],
      },
      {
        name: 'test_video_2',
        type: 'video',
        options: {
          videoUrl: '{{ video }}',
          duration: 4,
          musicVolumeLevel: 0.1,
        },
        filters: [
          {
            type: 'fadein',
            values: {
              color: '{{ colorTransition }}',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '{{ colorTransition }}',
            },
          },
        ],
      },
      {
        name: 'test_video_2',
        type: 'video',
        options: {
          videoUrl: '{{ video }}',
          duration: 4,
          musicVolumeLevel: 2,
        },
        filters: [
          {
            type: 'fadein',
            values: {
              color: '{{ colorTransition }}',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '{{ colorTransition }}',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  fast_and_curious: {
    global: {
      variables: {
        watermark: 'https://github.com/heristop/ffmpeg-template-assembly/raw/main/src/shared/assets/pictures/logo.png',
        colorsList: ['#FFFFFF', '#000000'],
      },
      orientation: 'landscape',
      musicEnabled: false,
      transitionDuration: 2,
    },
    sections: [
      {
        name: 'intro_1_1',
        type: 'color_background',
        options: {
          backgroundColor: '{{ color1 }}',
          duration: 0.5,
          musicVolumeLevel: 0.4,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 360,
              c: '{{ color2 }}@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 360,
              w: 1280,
              h: 360,
              c: '{{ color1 }}@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'fast',
              },
              fontcolor: '{{ color1 }}',
              fontsize: 192,
              x: '(w-text_w)/2 - 168',
              y: '(h-text_h)/2 - 70',
              fontfile: 'Quicksand.ttf',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'curious',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 192,
              x: '(w-text_w)/2 + 100 ',
              y: '(h-text_h)/2 + 27',
              fontfile: 'Quicksand.ttf',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'with {{ form_1_firstname }}',
              },
              fontcolor: '{{ color1 }}',
              fontsize: 40,
              x: '(w-tw) - 180',
              y: '(h-text_h)/2 + 200',
              fontfile: 'Quicksand.ttf',
              box: 1,
              boxcolor: '{{ color2 }}',
              boxborderw: 16,
            },
          },
        ],
      },
      {
        name: 'intro_1_2',
        type: 'color_background',
        options: {
          backgroundColor: '{{ color2 }}',
          duration: 0.5,
          musicVolumeLevel: 0.4,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 360,
              c: '{{ color1 }}@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 360,
              w: 1280,
              h: 360,
              c: '{{ color2 }}@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                fr: 'fast',
                en: 'fast',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 192,
              x: '(w-text_w)/2 - 168',
              y: '(h-text_h)/2 - 70',
              fontfile: 'Quicksand.ttf',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                fr: 'curious',
                en: 'curious',
              },
              fontcolor: '{{ color1 }}',
              fontsize: 192,
              x: '(w-text_w)/2 + 100 ',
              y: '(h-text_h)/2 + 27',
              fontfile: 'Quicksand.ttf',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'with {{ form_1_firstname }}',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 40,
              x: '(w-tw) - 180',
              y: '(h-text_h)/2 + 200',
              fontfile: 'Quicksand.ttf',
              box: 1,
              boxcolor: '{{ color1 }}',
              boxborderw: 16,
            },
          },
        ],
      },
      {
        name: 'intro_1_3',
        type: 'color_background',
        options: {
          backgroundColor: '{{ color2 }}',
          duration: 1.1,
          musicVolumeLevel: 0.4,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 360,
              c: '{{ color2 }}@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 360,
              w: 1280,
              h: 360,
              c: '{{ color1 }}@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                fr: 'fast',
                en: 'fast',
              },
              fontcolor: '{{ color1 }}',
              fontsize: 192,
              x: '(w-text_w)/2 - 168',
              y: '(h-text_h)/2 - 70',
              fontfile: 'Quicksand.ttf',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                fr: 'curious',
                en: 'curious',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 192,
              x: '(w-text_w)/2 + 100 ',
              y: '(h-text_h)/2 + 27',
              fontfile: 'Quicksand.ttf',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'with {{ form_1_firstname }}',
              },
              fontcolor: '{{ color1 }}',
              fontsize: 40,
              x: '(w-tw) - 180',
              y: '(h-text_h)/2 + 200',
              fontfile: 'Quicksand.ttf',
              box: 1,
              boxcolor: '{{ color2 }}',
              boxborderw: 16,
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  intertitle: {
    global: {
      variables: {
        watermark: 'https://github.com/heristop/ffmpeg-video-composer/raw/main/src/shared/assets/pictures/logo.png',
        colorsList: ['#FFFFFF'],
      },
      orientation: 'landscape',
      musicEnabled: false,
      transitionDuration: 0.5,
    },
    sections: [
      {
        name: 'test_intertitle',
        type: 'video',
        options: {
          useVideoSection: 'video_1',
          duration: 6,
          musicVolumeLevel: 0.4,
        },
        inputs: [
          {
            name: 'intertitles_border',
            url: 'https://github.com/heristop/ffmpeg-video-composer/raw/main/src/shared/assets/animations/white_border.zip',
            type: 'frame',
            options: {
              frequency: 0.04,
              overlay: '0:0',
              scale: '1280:720',
              persistent: true,
            },
            filters: [],
          },
          {
            name: 'watermark',
            url: '{{ watermark }}',
          },
        ],
        maps: [
          {
            inputs: ['@watermark'],
            filters: [
              {
                type: 'scale',
                values: {
                  h: -1,
                  w: 200,
                },
              },
            ],
            outputs: ['scaled_logo'],
          },
          {
            inputs: ['@video'],
            options: {
              useSectionFilters: true,
            },
            outputs: ['project_video'],
          },
          {
            inputs: ['@intertitles_border', 'scaled_logo'],
            filters: [
              {
                type: 'overlay',
                value: '50:50',
              },
            ],
            outputs: ['animation_and_logo'],
          },
          {
            inputs: ['project_video', 'animation_and_logo'],
            filters: [
              {
                type: 'overlay',
                value: '0:0',
              },
            ],
            outputs: ['final'],
          },
        ],
        filters: [
          {
            type: 'boxblur',
            value: '5',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '{{ color1 }}@0.15',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_firstname }} {{ form_1_lastname }}',
              },
              fontcolor: '#FFFFFF',
              fontsize: 40,
              x: '(w-text_w)/2',
              y: '(h-text_h)/1.4',
              fontfile: 'Inconsolata.ttf',
              alpha: "'if(lt(t,0.5),0,if(lt(t,1.5),(t-0.5)/1,if(lt(t,5),1,if(lt(t,7),(1-(t-6))/1,0))))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'Job: {{ form_1_job }}',
              },
              fontcolor: '#FFFFFF',
              fontsize: 40,
              x: '(w-text_w)/2',
              y: '(h-text_h)/1.4+60',
              fontfile: 'Inconsolata.ttf',
              alpha: "'if(lt(t,0.5),0,if(lt(t,1.5),(t-0.5)/1,if(lt(t,5),1,if(lt(t,7),(1-(t-6))/1,0))))'",
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#000000',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  local_music: {
    global: {
      variables: {
        colorTransition: 'blue',
      },
      music: {
        name: 'point_being_-_go_by_ocean___ryan_mccaffrey.mp3',
      },
      orientation: 'landscape',
      musicEnabled: true,
      transitionDuration: 2,
    },
    sections: [
      {
        name: 'earth',
        type: 'project_video',
        options: {
          duration: 6,
        },
        filters: [
          {
            type: 'fadein',
            values: {
              color: '{{ colorTransition }}',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  loop_music: {
    global: {
      variables: {
        colorsList: ['#FFFFFF'],
      },
      music: {
        name: 'popopop',
        url: 'https://github.com/heristop/ffmpeg-video-composer/raw/main/src/shared/assets/musics/pop.mp3',
      },
      orientation: 'landscape',
      musicEnabled: true,
      audioVolumeLevel: 4,
      transitionDuration: 0.5,
    },
    sections: [
      {
        name: 'test_loop_intro',
        type: 'video',
        options: {
          useVideoSection: 'video_4',
          duration: 6,
          musicVolumeLevel: 0.6,
        },
        filters: [
          {
            type: 'boxblur',
            value: '5',
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: 'black',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  picture: {
    global: {
      variables: {
        colorsList: ['#FFFFFF'],
      },
      orientation: 'landscape',
      musicEnabled: false,
      transitionDuration: 0.5,
    },
    sections: [
      {
        name: 'test_picture',
        type: 'image_background',
        options: {
          duration: 6,
          pictureUrl:
            'https://github.com/heristop/ffmpeg-video-composer/raw/main/src/shared/assets/pictures/SamplePNGImage_3mbmb.png',
        },
        filters: [
          {
            type: 'boxblur',
            value: '5',
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_firstname }} {{ form_1_lastname }}',
              },
              fontcolor: '#FFFFFF',
              fontsize: 40,
              x: '(w-text_w)/2',
              y: '(h-text_h)/1.4',
              fontfile: 'Inconsolata.ttf',
              alpha: "'if(lt(t,0.5),0,if(lt(t,1.5),(t-0.5)/1,if(lt(t,5),1,if(lt(t,7),(1-(t-6))/1,0))))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'Job: {{ form_1_job }}',
              },
              fontcolor: '#FFFFFF',
              fontsize: 40,
              x: '(w-text_w)/2',
              y: '(h-text_h)/1.4+60',
              fontfile: 'Inconsolata.ttf',
              alpha: "'if(lt(t,0.5),0,if(lt(t,1.5),(t-0.5)/1,if(lt(t,5),1,if(lt(t,7),(1-(t-6))/1,0))))'",
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#000000',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  portrait: {
    global: {
      variables: {
        colorsList: ['#FFFFFF'],
      },
      orientation: 'portrait',
      musicEnabled: false,
      transitionDuration: 0.5,
    },
    sections: [
      {
        name: 'test_portrait',
        type: 'video',
        options: {
          useVideoSection: 'video_portrait',
          duration: 6,
          musicVolumeLevel: 0.4,
          forceOriginalAspectRatio: true,
        },
        inputs: [],
        maps: [],
        filters: [
          {
            type: 'boxblur',
            value: '5',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 1280,
              c: '{{ color1 }}@0.15',
              t: 'fill',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#000000',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  premium_intro: {
    global: {
      orientation: 'landscape',
      musicEnabled: false,
      transitionDuration: 0.5,
    },
    sections: [
      {
        name: 'form_1',
        type: 'form',
        title: {
          en: 'Title card details',
        },
        description: {
          en: '',
        },
        options: {
          fields: [
            {
              name: 'form_1_firstname',
              maxLength: 20,
              label: {
                en: 'First name',
              },
            },
            {
              name: 'form_1_lastname',
              maxLength: 20,
              label: {
                en: 'Last name',
              },
            },
            {
              name: 'form_1_job',
              maxLength: 40,
              label: {
                en: 'Role / subtitle',
              },
            },
          ],
        },
      },
      {
        name: 'premium_intro',
        type: 'color_background',
        options: {
          backgroundColor: '#0d1b2a',
          duration: 4,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#0d1b2a@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 160,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 560,
              w: 1280,
              h: 160,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_firstname }} {{ form_1_lastname }}',
              },
              fontcolor: '#f5c518',
              fontsize: 132,
              x: '(w-text_w)/2',
              y: 248,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.5),0,if(lt(t,1.4),(t-0.5)/0.9,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 490,
              y: 412,
              w: 300,
              h: 5,
              c: '#f5c518@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_job }}',
              },
              fontcolor: '#e8eef7',
              fontsize: 34,
              x: '(w-text_w)/2',
              y: 446,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,1.0),0,if(lt(t,1.8),(t-1.0)/0.8,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#0d1b2a',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#0d1b2a',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  premium_quote: {
    global: {
      orientation: 'landscape',
      musicEnabled: false,
      transitionDuration: 0.5,
    },
    sections: [
      {
        name: 'premium_quote',
        type: 'color_background',
        options: {
          backgroundColor: '#f4f1ea',
          duration: 5,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#f4f1ea@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 14,
              h: 720,
              c: '#1b2a4a@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '“',
              },
              fontcolor: '#c2a14d',
              fontsize: 220,
              x: 150,
              y: 90,
              fontfile: 'PlayfairDisplay.ttf',
              alpha: "'if(lt(t,0.3),0,if(lt(t,1.0),(t-0.3)/0.7,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'Design is not just what it',
              },
              fontcolor: '#1b2a4a',
              fontsize: 60,
              x: 200,
              y: 250,
              fontfile: 'PlayfairDisplay.ttf',
              alpha: "'if(lt(t,0.8),0,if(lt(t,1.6),(t-0.8)/0.8,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'looks like. It is how it works.',
              },
              fontcolor: '#1b2a4a',
              fontsize: 60,
              x: 200,
              y: 330,
              fontfile: 'PlayfairDisplay.ttf',
              alpha: "'if(lt(t,1.2),0,if(lt(t,2.0),(t-1.2)/0.8,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 200,
              y: 448,
              w: 70,
              h: 4,
              c: '#c2a14d@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'STEVE JOBS',
              },
              fontcolor: '#7a6a3a',
              fontsize: 30,
              x: 200,
              y: 478,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,1.8),0,if(lt(t,2.6),(t-1.8)/0.8,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#f4f1ea',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#f4f1ea',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  premium_quote_portrait: {
    global: {
      orientation: 'portrait',
      musicEnabled: false,
      transitionDuration: 0.5,
    },
    sections: [
      {
        name: 'premium_quote_portrait',
        type: 'color_background',
        options: {
          backgroundColor: '#2a1a3e',
          duration: 5,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 1280,
              c: '#1a1030@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 426,
              c: '#2a1a3e@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 854,
              w: 720,
              h: 426,
              c: '#120a24@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'stay curious',
              },
              fontcolor: '#f2c14e',
              fontsize: 96,
              x: '(w-text_w)/2',
              y: 470,
              fontfile: 'Pacifico.ttf',
              alpha: "'if(lt(t,0.4),0,if(lt(t,1.3),(t-0.4)/0.9,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 310,
              y: 620,
              w: 100,
              h: 3,
              c: '#f2c14e@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'Every great build starts',
              },
              fontcolor: '#efe9f7',
              fontsize: 40,
              x: '(w-text_w)/2',
              y: 680,
              fontfile: 'PlayfairDisplay.ttf',
              alpha: "'if(lt(t,1.0),0,if(lt(t,1.8),(t-1.0)/0.8,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'with a single question.',
              },
              fontcolor: '#efe9f7',
              fontsize: 40,
              x: '(w-text_w)/2',
              y: 740,
              fontfile: 'PlayfairDisplay.ttf',
              alpha: "'if(lt(t,1.4),0,if(lt(t,2.2),(t-1.4)/0.8,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'L E C L A P   S T O R I E S',
              },
              fontcolor: '#a98fd6',
              fontsize: 26,
              x: '(w-text_w)/2',
              y: 980,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,2.0),0,if(lt(t,2.8),(t-2.0)/0.8,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#1a1030',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#1a1030',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  premium_reel_portrait: {
    global: {
      orientation: 'portrait',
      musicEnabled: false,
      transitionDuration: 0.5,
    },
    sections: [
      {
        name: 'premium_reel_portrait',
        type: 'color_background',
        options: {
          backgroundColor: '#101418',
          duration: 4,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 1280,
              c: '#101418@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 380,
              c: '#16202a@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 60,
              y: 470,
              w: 90,
              h: 10,
              c: '#ff4d4d@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'EP. 01',
              },
              fontcolor: '#ff4d4d',
              fontsize: 34,
              x: 60,
              y: 520,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,0.3),0,if(lt(t,1.0),(t-0.3)/0.7,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'BUILD IN',
              },
              fontcolor: '#ffffff',
              fontsize: 120,
              x: 56,
              y: 580,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.6),0,if(lt(t,1.4),(t-0.6)/0.8,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'PUBLIC',
              },
              fontcolor: '#ff4d4d',
              fontsize: 120,
              x: 56,
              y: 700,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.9),0,if(lt(t,1.7),(t-0.9)/0.8,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'Ship on device. No server. No wait.',
              },
              fontcolor: '#9aa7b4',
              fontsize: 30,
              x: 60,
              y: 870,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,1.4),0,if(lt(t,2.2),(t-1.4)/0.8,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 60,
              y: 1150,
              w: 600,
              h: 2,
              c: '#2a3744@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '@leclap',
              },
              fontcolor: '#ffffff',
              fontsize: 30,
              x: 60,
              y: 1180,
              fontfile: 'Oswald.ttf',
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#101418',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#101418',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  premium_titles: {
    global: {
      orientation: 'landscape',
      musicEnabled: false,
      transitionDuration: 0.6,
    },
    sections: [
      {
        name: 'title_card_1',
        type: 'color_background',
        options: {
          backgroundColor: '#0b0f14',
          duration: 3,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#0b0f14@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'A NEW WAY',
              },
              fontcolor: '#ffffff',
              fontsize: 140,
              x: '(w-text_w)/2',
              y: 230,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.4),0,if(lt(t,1.2),(t-0.4)/0.8,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'TO MAKE VIDEO',
              },
              fontcolor: '#00d4a0',
              fontsize: 140,
              x: '(w-text_w)/2',
              y: 370,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.7),0,if(lt(t,1.5),(t-0.7)/0.8,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#0b0f14',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#0b0f14',
            },
          },
        ],
      },
      {
        name: 'title_card_2',
        type: 'color_background',
        options: {
          backgroundColor: '#00d4a0',
          duration: 3,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#00d4a0@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 220,
              c: '#0b0f14@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 500,
              w: 1280,
              h: 220,
              c: '#0b0f14@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'DETERMINISTIC',
              },
              fontcolor: '#0b0f14',
              fontsize: 110,
              x: '(w-text_w)/2',
              y: 290,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.4),0,if(lt(t,1.1),(t-0.4)/0.7,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'on-device   .   agent-callable',
              },
              fontcolor: '#0b0f14',
              fontsize: 34,
              x: '(w-text_w)/2',
              y: 410,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,0.8),0,if(lt(t,1.5),(t-0.8)/0.7,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '{{ transitionDuration }}',
              color: '#0b0f14',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#0b0f14',
            },
          },
        ],
      },
      {
        name: 'title_card_3',
        type: 'color_background',
        options: {
          backgroundColor: '#0b0f14',
          duration: 3,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#0b0f14@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 540,
              y: 300,
              w: 200,
              h: 6,
              c: '#00d4a0@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'LECLAP',
              },
              fontcolor: '#ffffff',
              fontsize: 150,
              x: '(w-text_w)/2',
              y: 340,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.5),0,if(lt(t,1.3),(t-0.5)/0.8,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '{{ transitionDuration }}',
              color: '#0b0f14',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '0.8',
              st: '{{ transitionStartTime }}',
              color: '#0b0f14',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  sample: {
    global: {
      variables: {
        watermark: 'https://github.com/heristop/ffmpeg-video-composer/raw/main/src/shared/assets/pictures/logo.png',
        videoOutro: 'https://github.com/heristop/ffmpeg-video-composer/raw/main/src/shared/assets/videos/outro.mp4',
        animatedIcon:
          'https://github.com/heristop/ffmpeg-video-composer/raw/main/src/shared/assets/animations/animation_icons.zip',
        colorsList: ['rgb(41 37 36)', 'rgb(250 250 249)'],
      },
      music: {
        name: 'default',
        url: 'https://github.com/heristop/ffmpeg-video-composer/raw/main/src/shared/assets/musics/point_being_-_go_by_ocean___ryan_mccaffrey.mp3',
      },
      orientation: 'landscape',
      musicEnabled: true,
      audioVolumeLevel: 1,
      transitionDuration: 0.5,
    },
    sections: [
      {
        name: 'intro_1',
        type: 'video',
        options: {
          useVideoSection: 'video_1',
          duration: 6,
          musicVolumeLevel: 0.4,
        },
        inputs: [
          {
            name: 'intertitles_border',
            url: 'https://github.com/heristop/ffmpeg-video-composer/raw/main/src/shared/assets/animations/white_border.zip',
            type: 'frame',
            options: {
              frequency: 0.04,
              overlay: '0:0',
              scale: '1280:720',
              persistent: true,
            },
            filters: [],
          },
          {
            name: 'watermark',
            url: '{{ watermark }}',
          },
        ],
        maps: [
          {
            inputs: ['@watermark'],
            filters: [
              {
                type: 'scale',
                values: {
                  h: -1,
                  w: 100,
                },
              },
            ],
            outputs: ['scaled_logo'],
          },
          {
            inputs: ['@video'],
            options: {
              useSectionFilters: true,
            },
            outputs: ['video'],
          },
          {
            inputs: ['@intertitles_border', 'scaled_logo'],
            filters: [
              {
                type: 'overlay',
                value: '50:50',
              },
            ],
            outputs: ['animation_and_logo'],
          },
          {
            inputs: ['video', 'animation_and_logo'],
            filters: [
              {
                type: 'overlay',
                value: '0:0',
              },
            ],
            outputs: ['final'],
          },
        ],
        filters: [
          {
            type: 'boxblur',
            value: '5',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '{{ color1 }}@0.2',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_firstname }} {{ form_1_lastname }}',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 40,
              x: '(w-text_w)/2',
              y: '(h-text_h)/1.4',
              fontfile: 'Rubik+Doodle+Shadow.ttf',
              alpha: "'if(lt(t,0.5),0,if(lt(t,1.5),(t-0.5)/1,if(lt(t,5),1,if(lt(t,7),(1-(t-6))/1,0))))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '“{{ form_1_job }}”',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 40,
              x: '(w-text_w)/2',
              y: '(h-text_h)/1.4+60',
              fontfile: 'Rubik+Doodle+Shadow.ttf',
              alpha: "'if(lt(t,0.5),0,if(lt(t,1.5),(t-0.5)/1,if(lt(t,5),1,if(lt(t,7),(1-(t-6))/1,0))))'",
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '{{ color1 }}',
            },
          },
        ],
      },
      {
        name: 'form_1',
        type: 'form',
        title: {
          fr: 'Des infos avant de commencer',
          en: 'A few info before we start',
        },
        description: {
          fr: '',
          en: '',
        },
        options: {
          fields: [
            {
              name: 'form_1_firstname',
              maxLength: 30,
              label: {
                fr: 'Prénom',
                en: 'First name',
              },
            },
            {
              name: 'form_1_lastname',
              maxLength: 30,
              label: {
                en: 'Last name',
              },
            },
            {
              name: 'form_1_job',
              maxLength: 40,
              label: {
                en: 'Your Job',
              },
            },
          ],
        },
      },
      {
        name: 'video_1',
        type: 'project_video',
        title: {
          en: 'Tell us a little bit about you',
        },
        description: {
          en: 'Tell us your first and last name, the job that you do and the name of your company.',
        },
        options: {
          duration: 20000,
          musicVolumeLevel: 0.1,
        },
        inputs: [
          {
            name: 'animatedIcon',
            type: 'frame',
            options: {
              frequency: 0.3,
              overlay: '600:200',
              scale: '1280:720',
              persistent: false,
            },
            filters: [],
          },
        ],
        filters: [
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_firstname }} {{ form_1_lastname }}',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 40,
              x: '(w-tw-40)',
              y: '(h-th-220)',
              fontfile: 'Rubik.ttf',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_job }}',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 30,
              x: '(w-tw-40)',
              y: '(h-th-160)',
              fontfile: 'Rubik.ttf',
              box: 1,
              boxcolor: '{{ color2 }}@0.5',
              boxborderw: 10,
            },
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '{{ transitionDuration }}',
              color: '{{ color2 }}',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '{{ color1 }}',
            },
          },
        ],
      },
      {
        name: 'intertitle_1_1',
        type: 'color_background',
        options: {
          backgroundColor: '{{ color1 }}',
          duration: 0.5,
          musicVolumeLevel: 0.4,
          lowerCase: true,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 360,
              c: '{{ color2 }}@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 360,
              w: 1280,
              h: 360,
              c: '{{ color1 }}@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'drink',
              },
              fontcolor: '{{ color1 }}',
              fontsize: 192,
              x: '(w-text_w)/2 - 168',
              y: '(h-text_h)/2 - 68',
              fontfile: 'Rubik.ttf',
            },
          },
        ],
      },
      {
        name: 'intertitle_1_2',
        type: 'color_background',
        options: {
          backgroundColor: '{{ color2 }}',
          duration: 0.5,
          musicVolumeLevel: 0.4,
          lowerCase: true,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 360,
              c: '{{ color1 }}@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 360,
              w: 1280,
              h: 360,
              c: '{{ color2 }}@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'code',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 192,
              x: '(w-text_w)/2 - 168',
              y: '(h-text_h)/2 - 68',
              fontfile: 'Rubik.ttf',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'with {{ form_1_firstname }}',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 40,
              x: '(w-tw) - 180',
              y: '(h-text_h)/2 + 200',
              fontfile: 'Rubik.ttf',
              box: 1,
              boxcolor: '{{ color1 }}',
              boxborderw: 12,
            },
          },
        ],
      },
      {
        name: 'intertitle_1_3',
        type: 'color_background',
        options: {
          backgroundColor: '{{ color2 }}',
          duration: 1.1,
          musicVolumeLevel: 0.4,
          lowerCase: true,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 360,
              c: '{{ color2 }}@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 360,
              w: 1280,
              h: 360,
              c: '{{ color1 }}@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'drink',
              },
              fontcolor: '{{ color1 }}',
              fontsize: 192,
              x: '(w-text_w)/2 - 168',
              y: '(h-text_h)/2 - 68',
              fontfile: 'Rubik.ttf',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '& code',
              },
              fontcolor: '{{ color1 }}',
              fontsize: 194,
              x: '(w-text_w)/2 + 99',
              y: '(h-text_h)/2 + 26',
              fontfile: 'Rubik.ttf',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '& code',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 192,
              x: '(w-text_w)/2 + 100 ',
              y: '(h-text_h)/2 + 27',
              fontfile: 'Rubik.ttf',
            },
          },
        ],
      },
      {
        name: 'form_2',
        type: 'form',
        title: {
          en: '3 keywords to describe your job',
        },
        description: {
          fr: '',
          en: '',
        },
        options: {
          fields: [
            {
              name: 'form_2_keyword1',
              maxLength: 25,
              label: {
                en: 'Keyword 1',
              },
            },
            {
              name: 'form_2_keyword2',
              maxLength: 25,
              label: {
                en: 'Keyword 2',
              },
            },
            {
              name: 'form_2_keyword3',
              maxLength: 25,
              label: {
                en: 'Keyword 3',
              },
            },
            {
              name: 'form_2_keyword4',
              maxLength: 25,
              label: {
                en: 'Keyword 4',
              },
            },
          ],
        },
      },
      {
        name: 'video_2',
        type: 'project_video',
        title: {
          en: 'Make your speech',
        },
        description: {
          en: 'What are you going to make us discover?',
        },
        options: {
          duration: 45000,
          musicVolumeLevel: 0.1,
        },
        filters: [
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'Languages',
              },
              fontcolor: '{{ color1 }}',
              fontsize: 24,
              x: 'w-text_w-12',
              y: 60,
              fontfile: 'Rubik+Doodle+Shadow.ttf',
              box: 1,
              boxcolor: '{{ color2 }}@0.5',
              boxborderw: 12,
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                fr: '{{ form_2_keyword1 }}',
                en: '{{ form_2_keyword1 }}',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 24,
              x: 'w-text_w-12',
              y: 160,
              fontfile: 'Rubik+Doodle+Shadow.ttf',
              box: 1,
              boxcolor: '{{ color1 }}@0.5',
              boxborderw: 12,
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                fr: '{{ form_2_keyword2 }}',
                en: '{{ form_2_keyword2 }}',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 24,
              x: 'w-text_w-12',
              y: 240,
              fontfile: 'Rubik+Doodle+Shadow.ttf',
              box: 1,
              boxcolor: '{{ color1 }}@0.5',
              boxborderw: 12,
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_2_keyword3 }}',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 24,
              x: 'w-text_w-12',
              y: 320,
              fontfile: 'Rubik+Doodle+Shadow.ttf',
              box: 1,
              boxcolor: '{{ color1 }}@0.5',
              boxborderw: 12,
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_2_keyword4 }}',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 24,
              x: 'w-text_w-12',
              y: 400,
              fontfile: 'Rubik+Doodle+Shadow.ttf',
              box: 1,
              boxcolor: '{{ color1 }}@0.5',
              boxborderw: 12,
            },
          },
          {
            type: 'fadein',
            values: {
              color: '{{ color1 }}',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '{{ color1 }}',
            },
          },
        ],
      },
      {
        name: 'form_3',
        type: 'form',
        title: {
          en: 'Describe your work environment',
        },
        description: {
          fr: '',
          en: '',
        },
        options: {
          fields: [
            {
              name: 'form_3_keyword1',
              maxLength: 25,
              label: {
                en: '1 word to describe your work environment',
              },
            },
          ],
        },
      },
      {
        name: 'video_3',
        type: 'project_video',
        title: {
          en: 'Show the work environment',
        },
        description: {},
        options: {
          duration: 180000,
          musicVolumeLevel: 0.4,
          speed: 0.25,
          muteSection: true,
        },
        maps: [
          {
            inputs: ['1:v'],
            filters: [
              {
                type: 'setpts',
                value: '0.25*PTS',
              },
            ],
            outputs: ['final'],
          },
        ],
        filters: [
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_3_keyword1 }}',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 36,
              x: '(w-tw-40)',
              y: '(h-th-160)',
              fontfile: 'Rubik+Doodle+Shadow.ttf',
              box: 1,
              boxcolor: '{{ color1 }}@0.5',
              boxborderw: 10,
            },
          },
          {
            type: 'fadein',
            values: {
              color: '{{ color1 }}',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '{{ color1 }}',
            },
          },
        ],
      },
      {
        name: 'outro',
        type: 'video',
        options: {
          videoUrl: '{{ videoOutro }}',
          duration: 3,
          musicVolumeLevel: 0.2,
        },
        filters: [
          {
            type: 'fadein',
            values: {
              color: '{{ color1 }}',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '{{ color1 }}',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'Thank you for watching!',
              },
              fontcolor: '{{ color2 }}',
              fontsize: 60,
              x: '(w-text_w)/2',
              y: '(h-text_h)/1.4',
              fontfile: 'Rubik+Marker+Hatch.ttf',
              alpha: "'if(lt(t,0.5),0,if(lt(t,1.5),(t-0.5)/1,if(lt(t,5),1,if(lt(t,7),(1-(t-6))/1,0))))'",
            },
          },
        ],
      },
      {
        name: 'music_1',
        type: 'music',
        title: {
          en: 'Pick your music',
        },
        description: {
          en: '',
        },
        options: {},
      },
    ],
  } as TemplateDescriptor,
  video: {
    global: {
      variables: {
        videoSample: 'https://github.com/heristop/ffmpeg-video-composer/raw/main/src/shared/assets/videos/earth.mp4',
        colorTransition: '#FFFFFF',
      },
      orientation: 'landscape',
      musicEnabled: false,
      transitionDuration: 0.5,
    },
    sections: [
      {
        name: 'test_video',
        type: 'video',
        options: {
          videoUrl: '{{ videoSample }}',
          duration: 2,
        },
        filters: [
          {
            type: 'fadein',
            values: {
              color: '{{ colorTransition }}',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  video_speed: {
    global: {
      orientation: 'landscape',
      musicEnabled: false,
      transitionDuration: 0.5,
    },
    sections: [
      {
        name: 'video_3',
        type: 'project_video',
        title: {
          en: 'Show accelerated video',
        },
        description: {},
        options: {
          duration: 30000,
          speed: 0.25,
          muteSection: true,
        },
        maps: [
          {
            inputs: ['1:v'],
            filters: [
              {
                type: 'setpts',
                value: '0.25*PTS',
              },
            ],
            outputs: ['final'],
          },
        ],
        filters: [
          {
            type: 'fadein',
            values: {
              color: '#000000',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#000000',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
};
