// AUTO-GENERATED by scripts/embedTemplates.ts — do not edit by hand. Run `pnpm embed-templates`.
import type { TemplateDescriptor } from 'ffmpeg-video-composer';

export const builtinTemplates: Record<string, TemplateDescriptor> = {
  'fast-curious': {
    meta: {
      name: 'Fast & Curious',
      description: 'Punchy two-tone flash intro — your name on a bold cut, then your clip.',
    },
    global: {
      variables: {
        optionA1: 'Tea',
        optionB1: 'Coffee',
        optionA2: 'Beach',
        optionB2: 'Mountains',
        optionA3: 'Cats',
        optionB3: 'Dogs',
      },
      orientation: 'landscape',
      musicEnabled: true,
      music: {
        name: 'pop.mp3',
      },
      transition: {
        type: 'fade',
        duration: 0.2,
      },
      audio: {
        sourceVolume: 1,
        normalize: 'loudnorm',
      },
    },
    sections: [
      {
        type: 'partial',
        ref: 'logo-bumper',
      },
      {
        name: 'form_1',
        type: 'form',
        title: {
          en: "Who's the star?",
        },
        description: {
          en: '',
        },
        options: {
          fields: [
            {
              name: 'form_1_firstname',
              maxLength: 20,
              label: {
                en: 'First name',
              },
            },
          ],
        },
      },
      {
        type: 'partial',
        ref: 'question-flash',
        prefix: 'q1_',
        variables: {
          optionA: '{{ optionA1 }}',
          optionB: '{{ optionB1 }}',
          index: '1',
        },
      },
      {
        name: 'video_1',
        type: 'project_video',
        look: 'vivid',
        title: {
          en: 'Answer #1',
        },
        description: {
          en: '{{ optionA1 }} or {{ optionB1 }}? — film your answer',
        },
        options: {
          duration: 20,
          forceAspectRatio: true,
          countdown: true,
          countdownDuration: 3,
          musicVolume: 0.1,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 600,
              w: 1280,
              h: 120,
              c: '#141416@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 80,
              y: 628,
              w: 90,
              h: 5,
              c: '#ff2e4d@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ optionA1 }} or {{ optionB1 }}?',
              },
              fontcolor: '#f5f5f0',
              fontsize: 44,
              x: 80,
              y: 644,
              fontfile: 'BebasNeue.ttf',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#141416',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#141416',
            },
          },
        ],
      },
      {
        type: 'partial',
        ref: 'question-flash',
        prefix: 'q2_',
        variables: {
          optionA: '{{ optionA2 }}',
          optionB: '{{ optionB2 }}',
          index: '2',
        },
      },
      {
        name: 'video_2',
        type: 'project_video',
        look: 'vivid',
        title: {
          en: 'Answer #2',
        },
        description: {
          en: '{{ optionA2 }} or {{ optionB2 }}? — film your answer',
        },
        options: {
          duration: 20,
          forceAspectRatio: true,
          countdown: true,
          countdownDuration: 3,
          musicVolume: 0.1,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 600,
              w: 1280,
              h: 120,
              c: '#141416@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 80,
              y: 628,
              w: 90,
              h: 5,
              c: '#ff2e4d@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ optionA2 }} or {{ optionB2 }}?',
              },
              fontcolor: '#f5f5f0',
              fontsize: 44,
              x: 80,
              y: 644,
              fontfile: 'BebasNeue.ttf',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#141416',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#141416',
            },
          },
        ],
      },
      {
        type: 'partial',
        ref: 'question-flash',
        prefix: 'q3_',
        variables: {
          optionA: '{{ optionA3 }}',
          optionB: '{{ optionB3 }}',
          index: '3',
        },
      },
      {
        name: 'video_3',
        type: 'project_video',
        look: 'vivid',
        title: {
          en: 'Answer #3',
        },
        description: {
          en: '{{ optionA3 }} or {{ optionB3 }}? — film your answer',
        },
        options: {
          duration: 20,
          forceAspectRatio: true,
          countdown: true,
          countdownDuration: 3,
          musicVolume: 0.1,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 600,
              w: 1280,
              h: 120,
              c: '#141416@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 80,
              y: 628,
              w: 90,
              h: 5,
              c: '#ff2e4d@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ optionA3 }} or {{ optionB3 }}?',
              },
              fontcolor: '#f5f5f0',
              fontsize: 44,
              x: 80,
              y: 644,
              fontfile: 'BebasNeue.ttf',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#141416',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#141416',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  intro: {
    meta: {
      name: 'Intro',
      description: 'Cinematic title card — bold name, accent rule, graded backdrop.',
    },
    global: {
      orientation: 'landscape',
      musicEnabled: true,
      music: {
        name: 'arcadia.mp3',
      },
      transition: {
        type: 'fade',
        duration: 0.5,
      },
      audio: {
        sourceVolume: 1,
        normalize: 'loudnorm',
      },
    },
    sections: [
      {
        name: 'form_1',
        type: 'form',
        title: {
          en: 'Title card details',
        },
        description: {
          en: '',
        },
        options: {
          fields: [
            {
              name: 'form_1_firstname',
              maxLength: 20,
              label: {
                en: 'First name',
              },
            },
            {
              name: 'form_1_lastname',
              maxLength: 20,
              label: {
                en: 'Last name',
              },
            },
            {
              name: 'form_1_job',
              maxLength: 40,
              label: {
                en: 'Role / subtitle',
              },
            },
          ],
        },
      },
      {
        name: 'premium_intro',
        type: 'color_background',
        options: {
          backgroundColor: '#0d1b2a',
          duration: 4,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#0d1b2a@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 160,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 560,
              w: 1280,
              h: 160,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_firstname }} {{ form_1_lastname }}',
              },
              fontcolor: '#f5c518',
              fontsize: 132,
              x: '(w-text_w)/2',
              y: 248,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.5),0,if(lt(t,1.4),(t-0.5)/0.9,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 490,
              y: 412,
              w: 300,
              h: 5,
              c: '#f5c518@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_job }}',
              },
              fontcolor: '#e8eef7',
              fontsize: 34,
              x: '(w-text_w)/2',
              y: 446,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,1.0),0,if(lt(t,1.8),(t-1.0)/0.8,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#0d1b2a',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#0d1b2a',
            },
          },
        ],
      },
      {
        name: 'video_1',
        type: 'project_video',
        look: 'cinematic',
        title: {
          en: 'Record your clip',
        },
        description: {
          en: 'Your moment — graded in the title-card palette',
        },
        options: {
          duration: 30,
          forceAspectRatio: true,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 600,
              w: 1280,
              h: 120,
              c: '#0d1b2a@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 80,
              y: 628,
              w: 90,
              h: 5,
              c: '#f5c518@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_firstname }}',
              },
              fontcolor: '#f5c518',
              fontsize: 52,
              x: 80,
              y: 644,
              fontfile: 'BebasNeue.ttf',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#0d1b2a',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#0d1b2a',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  'landscape-spotlight': {
    meta: {
      name: 'Landscape Spotlight',
      description: 'Record a clip — graded intro + outro wrap it into a polished video.',
    },
    global: {
      orientation: 'landscape',
      musicEnabled: true,
      music: {
        name: 'arcadia.mp3',
      },
      transition: {
        type: 'fade',
        duration: 0.5,
      },
      audio: {
        sourceVolume: 1,
      },
    },
    sections: [
      {
        name: 'form_1',
        type: 'form',
        title: {
          en: 'Your details',
        },
        description: {
          en: '',
        },
        options: {
          fields: [
            {
              name: 'form_1_name',
              maxLength: 24,
              label: {
                en: 'Your name',
              },
            },
          ],
        },
      },
      {
        name: 'intro',
        type: 'color_background',
        transition: {
          type: 'wipeleft',
          duration: 0.4,
        },
        options: {
          backgroundColor: '#0d1b2a',
          duration: 2.4,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#0d1b2a@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 150,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 570,
              w: 1280,
              h: 150,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'PRESENTING',
              },
              fontcolor: '#e8eef7',
              fontsize: 30,
              x: '(w-text_w)/2',
              y: 250,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,0.3),0,if(lt(t,1.0),(t-0.3)/0.7,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_name }}',
              },
              fontcolor: '#f5c518',
              fontsize: 124,
              x: '(w-text_w)/2',
              y: 320,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.6),0,if(lt(t,1.5),(t-0.6)/0.9,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 540,
              y: 470,
              w: 200,
              h: 5,
              c: '#f5c518@1',
              t: 'fill',
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#0d1b2a',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#0d1b2a',
            },
          },
        ],
      },
      {
        name: 'video_1',
        type: 'project_video',
        look: 'cinematic',
        title: {
          en: 'Record your clip',
        },
        description: {
          en: 'Your moment — graded and captioned',
        },
        options: {
          duration: 30,
          forceAspectRatio: true,
          countdown: true,
          countdownDuration: 3,
          musicVolume: 0.1,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 600,
              w: 1280,
              h: 120,
              c: '#0d1b2a@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 80,
              y: 628,
              w: 90,
              h: 5,
              c: '#f5c518@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_name }}',
              },
              fontcolor: '#f5c518',
              fontsize: 52,
              x: 80,
              y: 644,
              fontfile: 'BebasNeue.ttf',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#0d1b2a',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#0d1b2a',
            },
          },
        ],
      },
      {
        name: 'outro',
        type: 'color_background',
        options: {
          backgroundColor: '#0d1b2a',
          duration: 2.6,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#0d1b2a@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 150,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 570,
              w: 1280,
              h: 150,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'LeClap',
              },
              fontcolor: '#f5c518',
              fontsize: 128,
              x: '(w-text_w)/2',
              y: 280,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.4),0,if(lt(t,1.2),(t-0.4)/0.8,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 540,
              y: 432,
              w: 200,
              h: 5,
              c: '#f5c518@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'made on your device',
              },
              fontcolor: '#e8eef7',
              fontsize: 30,
              x: '(w-text_w)/2',
              y: 458,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,0.9),0,if(lt(t,1.6),(t-0.9)/0.7,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#0d1b2a',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  'portrait-spotlight': {
    meta: {
      name: 'Portrait Spotlight',
      description: 'Record a vertical clip — graded intro + outro wrap it into a polished video.',
    },
    global: {
      orientation: 'portrait',
      musicEnabled: true,
      music: {
        name: 'arcadia.mp3',
      },
      transition: {
        type: 'fade',
        duration: 0.5,
      },
      audio: {
        sourceVolume: 1,
      },
    },
    sections: [
      {
        name: 'form_1',
        type: 'form',
        title: {
          en: 'Your details',
        },
        description: {
          en: '',
        },
        options: {
          fields: [
            {
              name: 'form_1_name',
              maxLength: 24,
              label: {
                en: 'Your name',
              },
            },
          ],
        },
      },
      {
        name: 'intro',
        type: 'color_background',
        transition: {
          type: 'wipeleft',
          duration: 0.4,
        },
        options: {
          backgroundColor: '#0d1b2a',
          duration: 2.4,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 1280,
              c: '#0d1b2a@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 220,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 1060,
              w: 720,
              h: 220,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'PRESENTING',
              },
              fontcolor: '#e8eef7',
              fontsize: 34,
              x: '(w-text_w)/2',
              y: 470,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,0.3),0,if(lt(t,1.0),(t-0.3)/0.7,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_name }}',
              },
              fontcolor: '#f5c518',
              fontsize: 120,
              x: '(w-text_w)/2',
              y: 560,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.6),0,if(lt(t,1.5),(t-0.6)/0.9,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 260,
              y: 740,
              w: 200,
              h: 5,
              c: '#f5c518@1',
              t: 'fill',
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#0d1b2a',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#0d1b2a',
            },
          },
        ],
      },
      {
        name: 'video_1',
        type: 'project_video',
        look: 'cinematic',
        title: {
          en: 'Record your clip',
        },
        description: {
          en: 'Your moment — graded and captioned',
        },
        options: {
          duration: 30,
          forceAspectRatio: true,
          countdown: true,
          countdownDuration: 3,
          musicVolume: 0.1,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 1100,
              w: 720,
              h: 180,
              c: '#0d1b2a@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 60,
              y: 1150,
              w: 90,
              h: 5,
              c: '#f5c518@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_name }}',
              },
              fontcolor: '#f5c518',
              fontsize: 52,
              x: 60,
              y: 1166,
              fontfile: 'BebasNeue.ttf',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#0d1b2a',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#0d1b2a',
            },
          },
        ],
      },
      {
        name: 'outro',
        type: 'color_background',
        options: {
          backgroundColor: '#0d1b2a',
          duration: 2.6,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 1280,
              c: '#0d1b2a@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 220,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 1060,
              w: 720,
              h: 220,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'LeClap',
              },
              fontcolor: '#f5c518',
              fontsize: 124,
              x: '(w-text_w)/2',
              y: 540,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.4),0,if(lt(t,1.2),(t-0.4)/0.8,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 260,
              y: 720,
              w: 200,
              h: 5,
              c: '#f5c518@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'made on your device',
              },
              fontcolor: '#e8eef7',
              fontsize: 34,
              x: '(w-text_w)/2',
              y: 748,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,0.9),0,if(lt(t,1.6),(t-0.9)/0.7,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#0d1b2a',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  'quote-portrait': {
    meta: {
      name: 'Quote (Portrait)',
      description: 'Vertical typographic quote card.',
    },
    global: {
      orientation: 'portrait',
      musicEnabled: true,
      music: {
        name: 'anxiety.mp3',
      },
      transition: {
        type: 'fade',
        duration: 0.5,
      },
      audio: {
        sourceVolume: 1,
      },
    },
    sections: [
      {
        name: 'premium_quote_portrait',
        type: 'color_background',
        options: {
          backgroundColor: '#2a1a3e',
          duration: 5,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 1280,
              c: '#1a1030@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 426,
              c: '#2a1a3e@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 854,
              w: 720,
              h: 426,
              c: '#120a24@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'stay curious',
              },
              fontcolor: '#f2c14e',
              fontsize: 96,
              x: '(w-text_w)/2',
              y: 470,
              fontfile: 'Pacifico.ttf',
              alpha: "'if(lt(t,0.4),0,if(lt(t,1.3),(t-0.4)/0.9,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 310,
              y: 620,
              w: 100,
              h: 3,
              c: '#f2c14e@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'Every great build starts',
              },
              fontcolor: '#efe9f7',
              fontsize: 40,
              x: '(w-text_w)/2',
              y: 680,
              fontfile: 'PlayfairDisplay.ttf',
              alpha: "'if(lt(t,1.0),0,if(lt(t,1.8),(t-1.0)/0.8,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'with a single question.',
              },
              fontcolor: '#efe9f7',
              fontsize: 40,
              x: '(w-text_w)/2',
              y: 740,
              fontfile: 'PlayfairDisplay.ttf',
              alpha: "'if(lt(t,1.4),0,if(lt(t,2.2),(t-1.4)/0.8,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'L E C L A P   S T O R I E S',
              },
              fontcolor: '#a98fd6',
              fontsize: 26,
              x: '(w-text_w)/2',
              y: 980,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,2.0),0,if(lt(t,2.8),(t-2.0)/0.8,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#1a1030',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#1a1030',
            },
          },
        ],
      },
      {
        name: 'video_1',
        type: 'project_video',
        look: 'cinematic',
        title: {
          en: 'Record your clip',
        },
        description: {
          en: 'Your story — graded in the layered-purple palette',
        },
        options: {
          duration: 30,
          forceAspectRatio: true,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 1110,
              w: 720,
              h: 130,
              c: '#1a1030@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 48,
              y: 1140,
              w: 80,
              h: 6,
              c: '#f2c14e@1',
              t: 'fill',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#1a1030',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#1a1030',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  quote: {
    meta: {
      name: 'Quote',
      description: 'Typographic quote card with staged text reveal.',
    },
    global: {
      orientation: 'landscape',
      musicEnabled: true,
      music: {
        name: 'autumn-day.mp3',
      },
      transition: {
        type: 'fade',
        duration: 0.5,
      },
      audio: {
        sourceVolume: 1,
      },
    },
    sections: [
      {
        name: 'premium_quote',
        type: 'color_background',
        look: 'cinematic',
        options: {
          backgroundColor: '#f4f1ea',
          duration: 5,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#f4f1ea@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 14,
              h: 720,
              c: '#1b2a4a@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '“',
              },
              fontcolor: '#c2a14d',
              fontsize: 220,
              x: 150,
              y: 90,
              fontfile: 'PlayfairDisplay.ttf',
              alpha: "'if(lt(t,0.3),0,if(lt(t,1.0),(t-0.3)/0.7,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'Design is not just what it',
              },
              fontcolor: '#1b2a4a',
              fontsize: 60,
              x: 200,
              y: 250,
              fontfile: 'PlayfairDisplay.ttf',
              alpha: "'if(lt(t,0.8),0,if(lt(t,1.6),(t-0.8)/0.8,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'looks like. It is how it works.',
              },
              fontcolor: '#1b2a4a',
              fontsize: 60,
              x: 200,
              y: 330,
              fontfile: 'PlayfairDisplay.ttf',
              alpha: "'if(lt(t,1.2),0,if(lt(t,2.0),(t-1.2)/0.8,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 200,
              y: 448,
              w: 70,
              h: 4,
              c: '#c2a14d@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'STEVE JOBS',
              },
              fontcolor: '#7a6a3a',
              fontsize: 30,
              x: 200,
              y: 478,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,1.8),0,if(lt(t,2.6),(t-1.8)/0.8,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#f4f1ea',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#f4f1ea',
            },
          },
        ],
      },
      {
        name: 'video_1',
        type: 'project_video',
        look: 'warm',
        title: {
          en: 'Record your clip',
        },
        description: {
          en: 'Your moment — graded in the editorial palette',
        },
        options: {
          duration: 30,
          forceAspectRatio: true,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 600,
              w: 1280,
              h: 120,
              c: '#1b2a4a@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 80,
              y: 628,
              w: 90,
              h: 5,
              c: '#c2a14d@1',
              t: 'fill',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#f4f1ea',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#f4f1ea',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  'reel-portrait': {
    meta: {
      name: 'Reel',
      description: 'Vertical social reel — graded backdrop, bold caption.',
    },
    global: {
      orientation: 'portrait',
      musicEnabled: true,
      music: {
        name: 'beachfront-celebration.mp3',
      },
      transition: {
        type: 'fade',
        duration: 0.5,
      },
      audio: {
        sourceVolume: 1,
      },
    },
    sections: [
      {
        name: 'premium_reel_portrait',
        type: 'color_background',
        options: {
          backgroundColor: '#101418',
          duration: 4,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 1280,
              c: '#101418@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 380,
              c: '#16202a@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 60,
              y: 470,
              w: 90,
              h: 10,
              c: '#ff4d4d@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'EP. 01',
              },
              fontcolor: '#ff4d4d',
              fontsize: 34,
              x: 60,
              y: 520,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,0.3),0,if(lt(t,1.0),(t-0.3)/0.7,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'BUILD IN',
              },
              fontcolor: '#ffffff',
              fontsize: 120,
              x: 56,
              y: 580,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.6),0,if(lt(t,1.4),(t-0.6)/0.8,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'PUBLIC',
              },
              fontcolor: '#ff4d4d',
              fontsize: 120,
              x: 56,
              y: 700,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.9),0,if(lt(t,1.7),(t-0.9)/0.8,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'Ship on device. No server. No wait.',
              },
              fontcolor: '#9aa7b4',
              fontsize: 30,
              x: 60,
              y: 870,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,1.4),0,if(lt(t,2.2),(t-1.4)/0.8,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 60,
              y: 1150,
              w: 600,
              h: 2,
              c: '#2a3744@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '@leclap',
              },
              fontcolor: '#ffffff',
              fontsize: 30,
              x: 60,
              y: 1180,
              fontfile: 'Oswald.ttf',
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#101418',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#101418',
            },
          },
        ],
      },
      {
        name: 'video_1',
        type: 'project_video',
        look: 'vivid',
        title: {
          en: 'Record your clip',
        },
        description: {
          en: 'Your reel — graded in the bold red palette',
        },
        options: {
          duration: 30,
          forceAspectRatio: true,
          framingGuide: {
            type: 'silhouette',
            position: 'right',
          },
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 1110,
              w: 720,
              h: 130,
              c: '#101418@0.6',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 48,
              y: 1140,
              w: 80,
              h: 8,
              c: '#ff4d4d@1',
              t: 'fill',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#101418',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#101418',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  titles: {
    meta: {
      name: 'Titles',
      description: 'Layered title sequence with eased typography.',
    },
    global: {
      orientation: 'landscape',
      musicEnabled: true,
      music: {
        name: 'americana.mp3',
      },
      transition: {
        type: 'fade',
        duration: 0.6,
      },
      audio: {
        sourceVolume: 1,
      },
    },
    sections: [
      {
        name: 'title_card_1',
        type: 'color_background',
        options: {
          backgroundColor: '#0b0f14',
          duration: 3,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#0b0f14@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'A NEW WAY',
              },
              fontcolor: '#ffffff',
              fontsize: 140,
              x: '(w-text_w)/2',
              y: 230,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.4),0,if(lt(t,1.2),(t-0.4)/0.8,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'TO MAKE VIDEO',
              },
              fontcolor: '#00d4a0',
              fontsize: 140,
              x: '(w-text_w)/2',
              y: 370,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.7),0,if(lt(t,1.5),(t-0.7)/0.8,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#0b0f14',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#0b0f14',
            },
          },
        ],
      },
      {
        name: 'title_card_2',
        type: 'color_background',
        options: {
          backgroundColor: '#00d4a0',
          duration: 3,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#00d4a0@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 220,
              c: '#0b0f14@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 500,
              w: 1280,
              h: 220,
              c: '#0b0f14@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'DETERMINISTIC',
              },
              fontcolor: '#0b0f14',
              fontsize: 110,
              x: '(w-text_w)/2',
              y: 290,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.4),0,if(lt(t,1.1),(t-0.4)/0.7,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'on-device   .   agent-callable',
              },
              fontcolor: '#0b0f14',
              fontsize: 34,
              x: '(w-text_w)/2',
              y: 410,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,0.8),0,if(lt(t,1.5),(t-0.8)/0.7,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '{{ transitionDuration }}',
              color: '#0b0f14',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#0b0f14',
            },
          },
        ],
      },
      {
        name: 'title_card_3',
        type: 'color_background',
        options: {
          backgroundColor: '#0b0f14',
          duration: 3,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#0b0f14@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 540,
              y: 300,
              w: 200,
              h: 6,
              c: '#00d4a0@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'LeClap',
              },
              fontcolor: '#ffffff',
              fontsize: 150,
              x: '(w-text_w)/2',
              y: 340,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.5),0,if(lt(t,1.3),(t-0.5)/0.8,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '{{ transitionDuration }}',
              color: '#0b0f14',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '0.8',
              st: '{{ transitionStartTime }}',
              color: '#0b0f14',
            },
          },
        ],
      },
      {
        name: 'video_1',
        type: 'project_video',
        look: 'cool',
        title: {
          en: 'Record your clip',
        },
        description: {
          en: 'Your moment — graded in the teal-and-charcoal brand',
        },
        options: {
          duration: 30,
          forceAspectRatio: true,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 600,
              w: 1280,
              h: 120,
              c: '#0b0f14@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 80,
              y: 628,
              w: 90,
              h: 5,
              c: '#00d4a0@1',
              t: 'fill',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#0b0f14',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#0b0f14',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
};
