// GENERATED by scripts/generate-font-advances.ts from the bundled fonts — do not edit.
// Advance widths in font units for code points FIRST..LAST, as comma-separated base-36 numbers; an
// empty slot = the font has no glyph. `extra` holds further script blocks (Hebrew, Arabic) for the
// fonts that draw them, from `start`.

export const FIRST_CODE_POINT = 32;
export const LAST_CODE_POINT = 383;

export interface FontAdvanceTable {
  unitsPerEm: number;
  advances: string;
  extra?: ReadonlyArray<{ start: number; advances: string }>;
}

export const FONT_ADVANCES: Readonly<Record<string, FontAdvanceTable>> = {
  'Rubik.ttf': {
    unitsPerEm: 1000,
    advances:
      '76,69,9g,jh,gk,kl,iq,5r,8v,8v,ce,hg,6l,dj,6m,cr,h4,b2,fk,g0,gj,fw,g6,dj,h6,fw,6p,77,dd,fv,dc,dz,my,i2,i5,i3,it,gg,fu,ig,jg,6z,h6,fz,f8,lo,j0,ie,hg,ie,hs,gt,fh,j7,hq,lw,gx,hk,g3,8d,cr,8d,bm,kx,8n,ew,g4,ew,g4,f6,a0,g5,gf,67,6h,dj,69,oe,ge,fi,g5,g5,9o,do,9z,g9,ew,lu,ee,es,dm,9k,63,9k,fn,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,76,61,f4,ia,g2,ga,69,fd,ag,n6,a7,gr,g5,go,n6,an,ai,fg,9b,9c,8n,ga,dn,96,8w,6q,a1,gr,kq,kv,nc,ds,i2,i2,i2,i2,i2,i2,pk,i3,gg,gg,gg,gg,6z,6z,6z,6z,iz,j0,ie,ie,ie,ie,ie,f1,ie,j7,j7,j7,j7,hk,hl,fs,ew,ew,ew,ew,ew,ew,oh,ew,f6,f6,f6,f6,67,67,67,67,fa,ge,fi,fi,fi,fi,fi,fp,fi,g9,g9,g9,g9,es,g5,es,i2,ew,i2,ew,i2,ew,i3,ew,i3,ew,i3,ew,i3,ew,it,g4,iz,g4,gg,f6,gg,f6,gg,f6,gg,f7,gg,f6,ig,g5,ig,g5,ig,g5,ig,g5,jg,gf,jg,gf,6z,67,6z,67,6z,67,7h,6s,6z,67,gd,co,h6,7h,fz,dj,dk,f8,69,f8,69,f8,6j,fi,7y,fg,6v,j0,ge,j0,ge,j0,ge,ge,j0,ge,ie,fi,ie,fi,ie,fi,p0,pv,hs,9o,hs,9o,hs,9o,gt,do,gt,do,gt,do,gt,do,,,fh,9z,fr,a7,j7,g9,j7,g9,j7,g9,j7,g9,j7,g9,j7,g9,lw,lu,hk,es,hk,g3,dm,g3,dm,g3,dm,7k',
    extra: [
      {
        start: 1424,
        advances:
          ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,0,0,0,0,0,0,0,0,0,0,0,0,0,,a9,,,0,0,,,,,0,,,,,,,,,fs,es,by,fg,gw,6d,aq,gx,hc,5x,fu,fn,ef,gw,gp,6d,ax,hl,fg,fu,fn,d9,e7,gy,eu,j7,hr,,,,,,,,bu,5x,9n,,,,,,,,,,,',
      },
      {
        start: 1536,
        advances:
          ',,,,,,,,,,,,5o,,,,,,,,,,,,,,,7k,,,,d4,,e3,7s,7s,cz,7s,m4,7s,po,dg,po,po,h4,h4,h4,f7,f7,8n,8n,xb,xb,yq,yq,jv,jv,er,er,,,,,,7i,p8,m8,o0,ji,f8,ig,dg,cz,m4,m4,0,0,0,0,0,0,0,0,0,0,0,0,,,,,,,,,,8q,8c,di,hr,ev,hb,fn,hh,hh,fu,ga,5j,5j,bo,po,m8,0,7s,,,,,,,,,,,,,po,,,,,,,,h4,,,,,,,,,,,,,,,,,,8n,,,,,,,,,p8,,,p8,,,,,nh,,,,,,nh,,,,,,,,,,,ig,,,,,,,,,,,,,,,,,,m4,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,8q,8c,di,hr,ff,hb,er,hh,hh,fu,,,,,,',
      },
    ],
  },
  'Oswald.ttf': {
    unitsPerEm: 1000,
    advances:
      '6d,5s,7e,di,dn,or,gu,3j,8a,78,b2,bj,57,8f,58,a9,ed,ai,da,d9,df,d8,dz,aq,dv,dy,5h,5z,ad,bj,ad,df,p4,do,ek,eb,en,bb,av,ev,fl,6w,8d,dr,b1,ic,eo,ez,dc,f1,ef,d5,bh,f3,e1,k9,de,dd,bl,9g,a9,8m,cb,9k,7q,bd,cf,bf,ca,bp,7z,c9,cd,6d,6e,bx,6d,iw,c7,bt,ce,cb,8x,ae,8k,c8,ap,gc,at,aw,9n,8c,6n,8x,cf,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6d,5s,as,b2,fa,cp,5w,bv,b4,ny,ad,cn,ar,,oo,7w,cl,bj,bq,bu,7p,c9,do,4w,9s,9g,bn,dd,q9,q9,oa,dc,do,do,do,do,do,do,hn,eb,bb,bb,bb,bb,6w,6w,6w,6w,ee,eo,ez,ez,ez,ez,ez,an,f0,f3,f3,f3,f3,dd,dz,eb,bd,bd,bd,bd,bd,bd,i3,bf,bp,bp,bp,bp,68,68,68,68,d3,c7,bt,bt,bt,bt,bt,9m,bs,c8,c8,c8,c8,aw,cf,aw,do,bd,do,bd,do,bd,eb,bf,eb,bf,eb,bf,eb,bf,en,em,ep,cm,bb,bp,bb,bp,bb,bp,bb,bp,bb,bp,ev,c9,ev,c9,ev,c9,ev,c9,fl,cd,fl,cd,6w,68,6w,68,6w,68,6w,6d,6w,68,f9,cr,8d,6e,dr,bx,by,b1,6d,b1,6d,b1,8l,b1,7w,b1,7f,eo,c7,eo,c7,eo,c7,dx,er,as,ez,bt,ez,bt,ez,bt,iz,j1,ef,8x,ef,8x,ef,8x,d5,ae,d5,ae,d5,ae,d5,ae,bh,8k,bh,97,bh,6s,f3,c8,f3,c8,f3,c8,f3,c8,f3,c8,f3,c8,k9,gc,dd,aw,dd,bl,9n,bl,9n,bl,9n,7z',
  },
  'BebasNeue.ttf': {
    unitsPerEm: 1000,
    advances:
      '4g,5u,9c,bg,b4,gd,bl,58,7o,7o,bq,b4,58,7i,58,at,b4,b4,b4,b4,b4,b4,b4,b4,b4,b4,58,58,b4,b4,b4,a3,jc,b5,b8,an,ba,a3,9k,av,bo,5c,7d,bi,9k,ey,bv,b4,aq,b4,b7,ac,a4,b6,am,fh,ba,ay,a2,7o,at,7o,b4,8c,dw,b5,b8,an,ba,a3,9k,av,bo,5c,7d,bi,9k,ey,bv,b4,aq,b4,b7,ac,a4,b6,am,fh,ba,ay,a2,7o,dw,7o,b4,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,4g,5u,b4,b4,b4,b4,dw,b4,dw,ki,7s,9c,b4,7i,ki,dw,b4,b4,7u,7u,dw,b9,ch,58,dw,7u,7u,9b,i5,i5,i5,a3,b5,b5,b5,b5,b5,b5,g4,an,a3,a3,a3,a3,5c,5c,5c,5c,br,bv,b4,b4,b4,b4,b4,b4,b4,b6,b6,b6,b6,ay,aq,bb,b5,b5,b5,b5,b5,b5,g4,an,a3,a3,a3,a3,5c,5c,5c,5c,br,bv,b4,b4,b4,b4,b4,b4,b4,b6,b6,b6,b6,ay,aq,ay,b5,b5,b5,b5,b5,b5,an,an,an,an,an,an,an,an,ba,ba,br,br,a3,a3,a3,a3,a3,a3,a3,a3,a3,a3,av,av,av,av,av,av,av,av,bo,bo,c6,c6,5c,5c,5c,5c,5c,5c,5c,5c,5c,5c,cp,cp,7d,7d,bi,bi,bi,9k,9k,9k,9k,9k,9k,9j,9j,a4,a4,bv,bv,bv,bv,bv,bv,f2,bv,bv,b4,b4,b4,b4,b4,b4,g1,g1,b7,b7,b7,b7,b7,b7,ac,ac,ac,ac,ac,ac,ac,ac,a4,a4,a4,a4,a4,a4,b6,b6,b6,b6,b6,b6,b6,b6,b6,b6,b6,b6,fh,fh,ay,ay,ay,a2,a2,a2,a2,a2,a2,',
  },
  'PlayfairDisplay.ttf': {
    unitsPerEm: 1000,
    advances:
      '6x,7a,8a,hp,ej,km,n9,59,86,86,do,gb,79,dv,70,ac,go,aa,db,cj,dq,bj,ed,ba,eg,e5,7e,7x,gw,hz,gw,cr,oe,hi,hb,j4,k3,gx,ft,jj,l1,9f,92,i7,gc,o7,jm,kl,g9,kl,i0,f0,h9,iy,hi,p5,hm,gf,gi,88,ac,88,ew,gf,7v,du,fn,di,g5,e2,98,eo,gc,85,7f,fa,7y,oo,gl,f8,g5,fn,cd,cf,9u,g5,dl,le,ef,e0,d8,8g,66,8g,i1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,6x,6x,d6,gq,ev,hz,68,e4,bw,ou,cv,dy,i8,dv,iu,bg,99,gl,9e,90,7v,,hx,7c,88,7b,cm,dx,j9,jg,ko,cl,hi,hi,hi,hi,hi,hi,nq,j4,gx,gx,gx,gx,9f,9f,9f,9f,k3,jm,kl,kl,kl,kl,kl,e6,kl,iy,iy,iy,iy,gf,g4,g8,du,du,du,du,du,du,kp,di,e2,e2,e2,e2,85,85,85,85,fe,gl,f8,f8,f8,f8,f8,i1,f8,g5,g5,g5,g5,e0,fj,e0,hi,du,hi,du,hi,du,j4,di,j4,di,j4,di,j4,di,k3,g5,k3,g5,gx,e2,gx,e2,gx,e2,gx,e2,gx,e2,jj,eo,jj,eo,jj,eo,jj,e1,l1,gc,l1,gc,9f,85,9f,85,9f,85,9f,85,9f,85,hz,fm,92,7f,i7,fa,fn,gc,7y,gc,7y,gc,7y,gc,bu,gc,7y,jm,gl,jm,gl,jm,gl,gl,jl,g3,kl,f8,kl,f8,kl,f8,ps,n7,i0,cd,i0,cd,i0,cd,f0,cf,f0,cf,f0,cf,f0,cf,h9,9u,h9,9u,h9,ag,iy,g5,iy,g5,iy,g5,iy,g5,iy,g5,iy,g5,p5,le,gf,e0,gf,gi,d8,gi,d8,gi,d8,98',
  },
  'Pacifico.ttf': {
    unitsPerEm: 1000,
    advances:
      '7d,9g,e6,jg,ek,ow,nn,82,h1,h1,eg,jg,75,b7,75,e5,f3,ag,fk,eg,g1,ee,f1,dt,e8,f1,75,75,jg,jg,jg,d8,s7,lu,mz,j2,n8,j2,js,mj,o9,dr,kn,q1,ip,y8,ok,mo,md,mo,og,j9,jd,oq,l7,xt,js,nn,k1,b9,e5,b9,jg,9u,go,d2,d5,a8,eb,ax,ab,db,dy,6u,72,el,92,ko,ds,cj,dd,dw,cn,bv,ax,cu,ch,jg,ep,db,cd,dm,92,dm,jg,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,7d,9g,cy,el,jg,dt,92,gv,go,hz,ax,h3,jg,b7,hz,go,ap,jg,ci,ci,go,cu,kj,75,go,ci,bc,h3,qj,sg,sr,d8,lu,lu,lu,lu,lu,lu,s7,j2,j2,j2,j2,j2,dr,dr,dr,dr,mt,ok,mo,mo,mo,mo,mo,jg,mo,oq,oq,oq,oq,nn,lk,gk,d2,d2,d2,d2,d2,d2,i5,a8,ax,ax,ax,ax,6u,6u,6u,6u,cj,ds,cj,cj,cj,cj,cj,jg,cr,cu,cu,cu,cu,db,e4,db,lu,d2,lu,d2,lu,d2,j2,a8,j2,a8,j2,a8,j2,a8,n8,d2,mt,d2,j2,ax,j2,ax,j2,ax,j2,ax,j2,ax,mj,db,mj,db,mj,db,mj,db,o9,dy,ns,dy,dr,6u,dr,6u,dr,6u,dr,6u,dr,6u,,,kn,72,q1,el,cx,ip,92,ip,92,ip,6l,ip,a3,ip,92,ok,ds,ok,ds,ok,ds,ds,ok,dr,mo,cj,mo,cj,mo,cj,v8,ik,og,cn,og,cn,og,cn,j9,bv,j9,bv,j9,bv,j9,bv,jd,ax,jd,9j,jd,9j,oq,cu,oq,cu,oq,cu,oq,cu,oq,cu,oq,cu,xt,jg,nn,db,nn,k1,cd,k1,cd,k1,cd,',
  },
  'RobotoMono.ttf': {
    unitsPerEm: 2048,
    advances:
      'y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5,y5',
  },
  'Anton.ttf': {
    unitsPerEm: 2048,
    advances:
      'dc,d1,oe,v3,qa,1o4,tl,c6,gk,gk,pq,k8,dg,hp,d0,n2,s4,it,s4,s4,s4,s4,s4,s4,s4,s4,dr,dy,ia,hp,ia,s0,1d6,rm,r8,qz,s2,nf,mp,rl,se,cw,qj,qv,mm,16g,sc,ro,qv,s3,r4,q9,mi,qy,qp,14i,rj,pe,nc,i3,n2,i3,qy,ks,i2,ri,sj,ry,sc,rs,fy,so,sr,du,ey,rx,e4,175,sd,s9,sj,sc,jq,r0,hd,se,q8,13m,q4,q8,ly,jc,cb,jd,s1,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,dc,cw,re,qy,rs,qc,cn,pk,r4,12e,mb,ww,mz,go,12e,ka,m4,ke,hh,hk,i2,rv,sb,dc,g0,c2,ml,ww,1ab,15b,1cm,s1,rm,rm,rm,rm,rm,rm,10f,qz,nf,nf,nf,nf,cw,cw,cw,cw,s2,sc,ro,ro,ro,ro,ro,jq,ro,qy,qy,qy,qy,pe,qb,rz,ri,ri,ri,ri,ri,ri,15l,ry,rs,rs,rs,rs,de,de,de,de,sn,sd,s9,s9,s9,s9,s9,j0,s9,se,se,se,se,q8,rz,q8,rm,ri,rm,ri,rm,ri,qz,ry,qz,ry,qz,ry,qz,ry,s2,11c,s2,sc,nf,rs,nf,rs,nf,rs,nf,rs,nf,rs,rl,so,rl,so,rl,so,rl,so,se,sr,sx,sr,cw,de,cw,de,cw,de,cw,du,cw,de,13f,ss,qj,ey,qv,rx,s1,mm,e4,mm,e4,mm,my,po,n8,np,ge,sc,sd,sc,sd,sc,sd,sd,ry,sd,ro,s9,ro,s9,ro,s9,10y,161,r4,jq,r4,jq,r4,jq,q9,r0,q9,r0,q9,r0,q9,r0,mi,hd,mi,ls,mi,hd,qy,se,qy,se,qy,se,qy,se,qy,se,qy,se,14i,13m,pe,q8,pe,nc,ly,nc,ly,nc,ly,fy',
  },
  'ArchivoBlack.ttf': {
    unitsPerEm: 1000,
    advances:
      '99,99,dw,ic,ij,rs,op,7q,at,at,fg,ic,99,99,99,7q,ij,ij,ij,ij,ij,ij,ij,ij,ij,ij,99,99,ic,ic,ic,gz,kk,lm,lm,lm,lm,k2,ij,n5,n5,at,ij,n5,ij,q8,n5,n5,k2,n5,lm,k2,k2,n5,lm,rs,lm,lm,k2,at,7q,at,ic,dw,99,ij,ij,ij,ij,ij,at,ij,ij,99,99,ij,99,rs,ij,ij,ij,ij,cc,gz,cc,ij,gz,q8,ij,gz,fg,at,7q,at,ic,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,99,99,ij,ij,ic,ij,7q,ij,99,m8,b4,ij,ic,99,m8,99,b4,ic,b4,b4,99,ij,nm,99,99,b4,b4,ij,rs,rs,rs,gz,lm,lm,lm,lm,lm,lm,rs,lm,k2,k2,k2,k2,at,at,at,at,lm,n5,n5,n5,n5,n5,n5,ic,n5,n5,n5,n5,n5,lm,k2,ij,ij,ij,ij,ij,ij,ij,rs,ij,ij,ij,ij,ij,99,99,99,99,ij,ij,ij,ij,ij,ij,ij,ic,ij,ij,ij,ij,ij,gz,ij,gz,lm,ij,lm,ij,lm,ij,lm,ij,lm,ij,lm,ij,lm,ij,lm,ng,lm,ij,k2,ij,k2,ij,k2,ij,k2,ij,k2,ij,n5,ij,n5,ij,n5,ij,n5,ij,n5,ij,n5,ij,at,99,at,99,at,99,at,99,at,99,sk,ik,ij,99,n5,ij,ij,ij,99,ij,99,ij,dw,ij,eu,ij,99,n5,ij,n5,ij,n5,ij,nu,mm,ix,n5,ij,n5,ij,n5,ij,rs,rs,lm,cc,lm,cc,lm,cc,k2,gz,k2,gz,k2,gz,k2,gz,k2,cc,k2,hd,k2,cc,n5,ij,n5,ij,n5,ij,n5,ij,n5,ij,n5,ij,rs,q8,lm,gz,lm,k2,fg,k2,fg,k2,fg,au',
  },
  'Bungee.ttf': {
    unitsPerEm: 1000,
    advances:
      '69,bs,hy,ku,i2,sn,la,9w,bx,bx,jy,ke,ao,bo,ao,9n,k7,gp,hr,hp,jp,hz,j9,hf,jr,j9,ao,ao,ju,ke,ju,i8,o3,ka,k5,hg,kq,i6,h6,jo,l3,gt,j4,kq,jb,nl,kx,kh,iy,kh,kn,i2,i8,kq,ka,n3,kh,jl,ic,bx,9n,bx,ju,ke,dw,ka,k5,hg,kq,i6,h6,jo,l3,gt,j4,kq,jb,nl,kx,kh,iy,kh,kn,i2,i8,kq,ka,n3,kh,jl,ic,cn,9n,cn,ke,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,69,br,hg,jb,mt,jj,9n,i2,dw,o3,eg,mk,ke,,fk,dw,df,ke,dh,dg,dw,jt,iy,a4,dw,cp,el,mk,xf,w8,xp,i8,ka,ka,ka,ka,ka,ka,rx,hg,i6,i6,i6,i6,gt,gt,gt,gt,l0,kx,kh,kh,kh,kh,kh,ke,kh,kq,kq,kq,kq,jl,j8,l3,ka,ka,ka,ka,ka,ka,rx,hg,i6,i6,i6,i6,gt,gt,gt,gt,l0,kx,kh,kh,kh,kh,kh,ke,kh,kq,kq,kq,kq,jl,j8,jl,ka,ka,ka,ka,ka,ka,hg,hg,hg,hg,hg,hg,hg,hg,kq,kq,l0,l0,i6,i6,i6,i6,i6,i6,i6,i6,i6,i6,jo,jo,jo,jo,jo,jo,jo,jo,l3,l3,ln,ln,gt,gt,gt,gt,gt,gt,gt,gt,gt,gt,ko,ko,j4,j4,kq,kq,kq,jb,jb,jb,jb,jb,jb,jb,jb,jl,jl,kx,kx,kx,kx,kx,kx,kx,kq,kq,kh,kh,kh,kh,kh,kh,s7,s7,kn,kn,kn,kn,kn,kn,i2,i2,i2,i2,i2,i2,i2,i2,i8,i8,i8,i8,i8,i8,kq,kq,kq,kq,kq,kq,kq,kq,kq,kq,kq,kq,n3,n3,jl,jl,jl,ic,ic,ic,ic,ic,ic,',
  },
  'AbrilFatface.ttf': {
    unitsPerEm: 1000,
    advances:
      '50,ah,9a,gw,fp,lc,mu,56,9r,9r,ep,eq,7a,9s,7d,9r,ig,bt,fc,fx,gr,f0,h4,e6,gz,h4,7d,7a,eq,eq,eq,g4,of,ja,ib,j6,kz,hc,gg,k3,kt,9v,ed,ke,gk,nc,im,ks,hm,ks,jw,go,iz,iz,j1,s7,jr,ht,h0,95,9r,94,fk,dw,dw,f9,gc,df,gc,ec,an,ei,h4,8t,8n,h8,8s,oo,h4,f3,gc,gc,dr,c2,ay,gt,es,n6,gj,es,eg,ah,8v,ah,eq,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,50,ah,eb,g5,eq,gx,8v,jf,dw,lp,cm,dq,eq,9g,cr,dw,95,eq,bl,bq,dw,ip,hg,8c,dw,bt,dl,dq,ms,ms,ms,g4,ja,ja,ja,ja,ja,ja,sp,j6,hc,hc,hc,hc,9v,9v,9v,9v,l7,im,ks,ks,ks,ks,ks,eq,ks,iz,iz,iz,iz,ht,hm,iq,f9,f9,f9,f9,f9,f9,lg,df,ec,ec,ec,ec,8t,8t,8t,8t,fk,h4,f3,f3,f3,f3,f3,eq,f6,gt,gt,gt,gt,es,gc,es,ja,f9,ja,f9,ja,f9,j6,df,j6,df,j6,df,j6,df,kz,ig,l7,g8,hc,ec,hc,ec,hc,ec,hc,ec,hc,ec,k3,ei,k3,ei,k3,ei,k3,ei,kt,h4,kt,h4,9v,8t,9v,8t,9v,8t,9v,8t,9v,8t,ny,hb,e3,8i,ke,h8,h8,gk,8s,gk,8s,gk,ap,gk,c5,gk,8y,im,h4,im,h4,im,h4,ij,im,gy,ks,f3,ks,f3,ks,f3,t1,n4,jw,dr,jw,dr,jw,dr,go,c2,go,c2,go,bw,go,c2,iz,ao,iz,ay,iz,ao,iz,gt,iz,gt,iz,gt,iz,gt,iz,gt,iz,gt,s7,n6,ht,es,ht,h0,dw,h0,dw,h0,dw,an',
  },
  'Righteous.ttf': {
    unitsPerEm: 2048,
    advances:
      'fx,fn,na,vx,q2,12z,rn,dl,jz,jz,xk,rn,f1,u3,ez,rw,10j,i3,wh,xe,zw,xc,z0,td,z6,z2,fr,fr,r7,uo,r7,yb,zu,12c,11w,10f,117,ww,vz,11u,139,fd,nq,zk,w1,1an,139,189,10j,189,113,yr,ww,12c,y9,1an,yn,za,xe,lo,rw,lo,gq,y1,ct,yl,xz,tp,yj,tv,mj,yl,vz,df,dj,uo,df,17d,vz,wy,yn,yl,nk,tt,ox,vz,ua,172,u3,w1,rf,qk,f7,qk,po,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,fx,fn,qc,12r,pu,117,fb,wf,h4,11b,po,142,u5,nu,p1,e2,lq,td,k9,k7,ct,wj,19z,ev,bu,d7,ol,140,10x,109,14c,y9,12c,12c,12c,12c,12c,12c,1k9,10f,ww,ww,ww,ww,fd,fd,fd,fd,12a,139,189,189,189,189,189,r9,189,12c,12c,12c,12c,za,109,1ab,yl,yl,yl,yl,yl,yl,1jj,tp,tv,tv,tv,tv,df,df,df,df,x2,vz,wy,wy,wy,wy,wy,s4,wy,vz,vz,vz,vz,w1,yn,w1,12c,yl,12c,yl,12c,yl,10f,tp,10f,tp,10f,tp,10f,tp,117,164,12a,yj,ww,tv,ww,tv,ww,tv,ww,tv,ww,tv,11u,yl,11u,yl,11u,yl,11u,yl,139,vz,139,vz,fd,df,fd,df,fd,df,fd,df,fd,df,133,qz,nq,dj,zk,uo,uo,w1,df,w1,df,w1,l0,16e,qe,xc,i7,139,vz,139,vz,139,vz,13j,139,vz,189,wy,189,wy,189,wy,1s2,1gm,113,nk,113,nk,113,nk,yr,tt,yr,tt,yr,tt,yr,tt,ww,ox,ww,wh,ww,ox,12c,vz,12c,vz,12c,vz,12c,vz,12c,vz,12c,vz,1an,172,za,w1,za,xe,rf,xe,rf,xe,rf,',
  },
  'Lobster.ttf': {
    unitsPerEm: 1000,
    advances:
      '61,75,9t,ib,f8,m4,iy,5g,c5,bh,eb,ca,60,82,7b,8n,f6,8t,do,ea,d8,ed,dw,cw,dv,dl,7f,7o,9y,eb,a2,c9,j4,ik,ht,dt,if,cr,cr,g2,ih,af,ew,gp,aj,lv,ik,ih,fx,ih,gp,fu,dd,jw,h3,qq,h8,h8,f2,b4,a2,b4,bp,cc,5l,em,cc,ao,el,ao,7f,e3,e1,7f,6o,ee,7f,kw,e1,c7,d0,di,ag,am,7f,e1,bi,id,ei,di,bw,9s,es,9s,bz,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,61,63,ao,cn,dw,fi,es,f2,aw,gb,9l,gd,cc,82,fd,ce,8q,db,94,9c,8s,e1,f2,c2,6b,6d,95,ga,kt,kp,n8,c7,ik,ik,ik,ik,ik,ik,l8,dt,cr,cr,cr,cr,af,af,af,af,if,j2,ih,ih,ih,ih,ih,bi,ia,jw,jw,jw,jw,h8,g7,dc,em,em,em,em,em,em,i2,ao,ao,ao,ao,ao,7f,7f,7f,7f,em,e1,c1,c7,c1,c1,c1,bj,bw,e1,e1,e1,e1,e1,d5,e1,ik,em,ik,em,ik,em,dt,ao,dt,ao,dt,ao,dt,ao,if,el,if,el,cr,ao,cr,ao,cr,ao,cr,ao,cr,ao,g2,e3,g2,e3,g2,e3,g2,e3,ih,e1,ih,e1,af,7f,af,7f,af,7f,af,7f,af,7f,if,e3,ew,6o,gp,ee,ee,aj,7f,aj,7f,aj,7f,gt,9t,aw,7y,ji,e1,ik,e1,ik,e1,e1,k3,e1,ih,c1,ih,c1,ih,c1,ni,if,gp,ag,gp,ag,gp,ag,fu,am,fu,am,fu,am,fu,a9,dd,7f,dd,7f,dd,7f,jw,e1,jw,e1,jw,e1,jw,e1,jw,e1,jw,e1,qq,id,h8,e1,h8,f2,bw,eq,bw,f2,bw,7f',
  },
  'NotoSansArabic.ttf': {
    unitsPerEm: 1000,
    advances:
      '78,7h,bc,hy,fw,n3,kc,69,8c,8c,fb,fw,7g,8y,7g,ac,fw,fw,fw,fw,fw,fw,fw,fw,fw,fw,7g,7g,fw,fw,fw,c2,oz,hr,i2,hk,ka,fg,ef,k8,kl,9f,7l,h7,ek,p7,l4,lp,gt,lp,ha,f9,fg,kb,go,pu,ga,fq,fw,95,ac,95,fw,cc,7t,fl,h3,dc,h3,fo,9k,h3,h6,76,76,eu,76,pz,h6,gt,h3,h3,bh,db,a1,h6,e4,lu,ep,e6,d2,ak,fb,ak,fw,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,78,7h,fw,fw,,fw,,e9,g4,n4,9x,e5,,,n4,dw,bw,,,,7t,,i7,7g,69,,ag,e5,,,,c2,hr,hr,hr,hr,hr,hr,oh,hk,fg,fg,fg,fg,9f,9f,9f,9f,ka,l4,lp,lp,lp,lp,lp,fw,lp,kb,kb,kb,kb,fq,gt,hj,fl,fl,fl,fl,fl,fl,o0,dc,fo,fo,fo,fo,76,76,76,76,gt,h6,gt,gt,gt,gt,gt,fw,gt,h6,h6,h6,h6,e6,h3,e6,hr,fl,hr,fl,hr,fl,hk,dc,,,hk,dc,hk,dc,ka,h3,ka,h5,fg,fo,,,fg,fo,fg,fo,fg,fo,,,k8,h3,k8,h3,k8,h3,,,kl,h6,,,9f,76,,,9f,76,9f,76,,,,,h7,eu,,ek,76,ek,76,ek,76,,,ek,76,l4,h6,l4,h6,l4,h6,,l4,h6,lp,gt,,,lp,gt,ps,qa,ha,bh,ha,bh,ha,bh,f9,db,,,f9,db,f9,db,,,fg,a1,,,,,kb,h6,kb,h6,kb,h6,kb,h6,kb,h6,pu,lu,fq,e6,fq,fw,d2,fw,d2,fw,d2,',
    extra: [
      {
        start: 1536,
        advances:
          'vq,15s,u3,10c,1kl,y2,ha,ha,ut,i1,n5,cf,94,a5,p4,eh,0,0,0,0,0,0,0,0,0,0,0,9k,go,gs,81,c2,l4,bf,6j,6j,cf,6m,l4,6m,rl,b9,rl,rl,hr,hr,hr,d9,d9,a7,a7,xl,xl,10a,10a,lw,lw,e3,e3,od,od,l4,l4,l4,7i,rb,li,oi,jb,dg,j1,io,cf,l4,l4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,fw,fw,fw,fw,fw,fw,fw,fw,fw,fw,d5,6t,6t,du,rl,li,0,6j,6j,6m,bf,i1,nu,nu,wj,rl,rl,rl,rl,rl,rl,rl,rl,hr,hr,ib,hr,hr,ib,ib,d9,d9,d9,d9,d9,d9,d9,d9,d9,a7,a7,a7,a7,a7,a7,a7,a7,a7,xl,xl,xl,10a,10a,lw,e3,rb,rb,rb,rb,rb,rb,li,li,od,sa,od,oi,oi,oi,od,od,od,od,od,od,jb,jb,jb,jb,j1,j1,j1,j1,j1,io,ib,b9,b9,b9,b9,cf,cf,cf,cf,cf,cf,cf,cf,l4,l4,l4,cf,l4,l4,q6,q6,8b,b9,0,0,0,0,0,0,0,122,rr,0,0,0,0,0,0,51,9r,0,0,gw,0,0,0,0,d9,a7,fw,fw,fw,fw,fw,fw,fw,fw,fw,fw,xl,10a,e3,bf,dg,io',
      },
    ],
  },
  'NotoSansHebrew.ttf': {
    unitsPerEm: 1000,
    advances:
      '7i,6w,b1,i4,fx,nn,ki,61,86,86,f6,g0,6e,8x,6u,a7,g0,g0,g0,g0,g0,g0,g0,g0,g0,g0,6u,6x,g0,g0,g0,cg,ol,hl,ho,hf,jo,fa,e6,k8,k9,9i,7o,gu,ev,om,kt,le,gj,le,h3,fg,ex,k9,h0,px,gd,fp,ge,8t,a7,8t,fd,c0,8o,fd,gu,dt,gu,ft,92,gu,gx,6z,6z,er,6z,p8,gx,gm,gu,gu,be,dc,ac,gx,du,ld,ew,ds,d7,ad,el,ad,g0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,7e,6w,g0,g0,,g0,,e7,g9,n1,9q,dv,,,n1,dw,bu,,,,8o,,i3,6u,6d,,a7,dv,,,,cg,hl,hl,hl,hl,hl,hl,n4,hf,fa,fa,fa,fa,9i,9i,9i,9i,jo,kt,le,le,le,le,le,g0,le,k9,k9,k9,k9,fp,gh,hg,fd,fd,fd,fd,fd,fd,oi,dt,ft,ft,ft,ft,6z,6z,6z,6z,gb,gx,gm,gm,gm,gm,gm,g0,gx,gx,gx,gx,gx,ds,gu,ds,hl,fd,hl,fd,hl,fd,hf,dt,,,hf,dt,hf,dt,jo,gu,jo,h0,fa,ft,,,fa,ft,fa,ft,fa,ft,,,k8,gu,k8,gu,k8,gu,,,kf,h1,,,9i,6z,,,9i,6z,9i,6z,,,,,gu,er,,ev,6z,ev,6z,ev,6z,,,f5,7y,kt,gx,kt,gx,kt,gx,,,,,,,,le,gm,pl,r0,h3,be,,,h3,be,fg,dc,,,fg,dc,fg,dc,,,ex,ac,,,,,k9,gx,,,k9,gx,k9,gx,k9,gx,px,ld,fp,ds,fp,ge,d7,ge,d7,ge,d7,',
    extra: [
      {
        start: 1424,
        advances:
          ',0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,90,0,el,0,0,6u,0,0,b1,0,,,,,,,,,hk,fw,ae,f2,hf,8d,96,ie,hm,87,f5,eb,ei,j0,ic,95,aj,hv,gh,h8,gp,ep,fg,hf,ej,ka,j1,,,,,hl,gd,gq,gn,56,a5,,,,,,,,,,,',
      },
    ],
  },
};
