import { cpSync, mkdirSync, readdirSync, writeFileSync } from 'node:fs';
import { basename, dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, '..');

const libDir = resolve(root, 'packages/leclap-creative-kit/src/library');

// Plain ANSI, no dependency — and dropped entirely when the output isn't a TTY (CI logs, pipes).
const color = process.stdout.isTTY && !process.env.NO_COLOR;
const paint = (code: number, text: string): string => (color ? `[${code}m${text}[0m` : text);
const bold = (text: string): string => paint(1, text);
const dim = (text: string): string => paint(2, text);
const green = (text: string): string => paint(32, text);

type CopyDest = { src: string; dest: string; include?: string[] };

const destinations: CopyDest[] = [
  {
    src: resolve(libDir, 'musics'),
    dest: resolve(root, 'apps/leclap-web/public/musics'),
  },
  {
    src: resolve(libDir, 'musics'),
    dest: resolve(root, 'apps/leclap-expo/assets/musics'),
  },
  {
    src: resolve(libDir, 'backgrounds'),
    dest: resolve(root, 'apps/leclap-web/public/backgrounds'),
  },
  {
    src: resolve(libDir, 'backgrounds'),
    dest: resolve(root, 'apps/leclap-expo/assets/backgrounds'),
  },
  {
    src: resolve(libDir, 'fonts'),
    dest: resolve(root, 'apps/leclap-web/public/fonts'),
  },
  {
    src: resolve(libDir, 'fonts'),
    dest: resolve(root, 'apps/leclap-expo/assets/fonts'),
  },
  {
    src: resolve(libDir, 'animations'),
    dest: resolve(root, 'apps/leclap-web/public/assets/animations'),
  },
  {
    src: resolve(libDir, 'animations'),
    dest: resolve(root, 'apps/leclap-expo/assets/animations'),
  },
  {
    src: resolve(libDir, 'musics'),
    dest: resolve(root, 'apps/leclap-web/public/assets/musics'),
  },
  {
    src: resolve(libDir, 'pictures'),
    dest: resolve(root, 'apps/leclap-web/public/assets/pictures'),
  },
  {
    src: resolve(libDir, 'videos'),
    dest: resolve(root, 'apps/leclap-web/public/assets/videos'),
  },
  {
    // The RN app only needs the brand bumpers bundled (the descriptor-referenced videos); the rest
    // are sample clips that would bloat the binary. Web ships the full set above.
    src: resolve(libDir, 'videos'),
    dest: resolve(root, 'apps/leclap-expo/assets/videos'),
    include: ['leclap_bumper.mp4', 'leclap_bumper_portrait.mp4'],
  },
];

console.log(`\n${bold('Staging creative-kit assets')}`);

let total = 0;

for (const { src, dest, include } of destinations) {
  mkdirSync(dest, { recursive: true });
  const files = include ?? readdirSync(src);

  for (const file of files) {
    cpSync(resolve(src, file), resolve(dest, file));
  }

  total += files.length;

  const count = String(files.length).padStart(3);
  console.log(`  ${green('✓')} ${basename(src).padEnd(11)} ${dim(count)} ${dim('→')} ${dim(relative(root, dest))}`);
}

console.log(`\n${green('✓')} ${bold(`${total} files`)} staged across ${destinations.length} targets\n`);

// Emit the animation manifest the web reads (a static, HMR-friendly list — more reliable than a
// cross-package import.meta.glob, which the dev server doesn't re-scan when files land in the library).
const animationFiles = readdirSync(resolve(libDir, 'animations'))
  .filter((file) => /\.(apng|webp|gif|webm)$/i.test(file))
  .sort();

const manifestPath = resolve(root, 'apps/leclap-web/src/data/animations.generated.ts');
const manifest = `// AUTO-GENERATED by scripts/copy-core-assets.ts — do not edit.
// Every animation overlay in the creative-kit library, served from /public/assets/animations. Re-run
// the copy step (it runs on web build/start) after adding a file to the library to refresh this list.
export const ANIMATION_FILES: string[] = ${JSON.stringify(animationFiles, null, 2)};
`;
writeFileSync(manifestPath, manifest);
console.log(`${green('✓')} ${dim(`animation manifest (${animationFiles.length}) → ${relative(root, manifestPath)}`)}`);

// Expo needs STATIC require()s (Metro can't build a path from a variable), so emit a literal require
// map of the same files. Bundled for on-device staging + the picker thumbnails.
const expoAssetsPath = resolve(root, 'apps/leclap-expo/src/data/animation-assets.generated.ts');
const expoEntries = animationFiles.map((file) => `  '${file}': require('../../assets/animations/${file}'),`).join('\n');
const expoAssets = `// AUTO-GENERATED by scripts/copy-core-assets.ts — do not edit.
// Bundled animation overlays for the RN app, keyed by filename → Metro asset id. Re-run the copy step
// (it runs on expo start) after adding a file to the library to refresh this map.
export const ANIMATION_ASSETS: Record<string, number> = {
${expoEntries}
};
`;
writeFileSync(expoAssetsPath, expoAssets);
console.log(
  `${green('✓')} ${dim(`expo animation assets (${animationFiles.length}) → ${relative(root, expoAssetsPath)}`)}\n`
);
