// Rasterize the bundled colour-emoji subset that text lowering composites as image overlays (drawtext
// draws monochrome outlines only, so colour emoji are drawn as PNGs next to the text).
//
// Source: the Twemoji graphics (CC-BY 4.0, https://github.com/jdecked/twemoji), read from the
// `@twemoji/svg` npm package so the script works through an npm registry proxy. Each emoji is
// rendered to a 72x72 PNG named by its code-point sequence (lowercase hex joined by '-', the variation
// selector U+FE0F dropped outside ZWJ sequences) into packages/leclap-creative-kit/src/library/emoji/,
// and the engine's manifest (src/core/emoji-manifest.generated.ts) is rewritten to list them.
//
// Run: `pnpm gen:emoji` (or `node scripts/gen-emoji.ts --svg-dir <dir with the .svg files>`).
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = resolve(root, 'packages/leclap-creative-kit/src/library/emoji');
const manifestPath = resolve(root, 'packages/ffmpeg-video-composer/src/core/emoji-manifest.generated.ts');
const SVG_PACKAGE = '@twemoji/svg@15.0.0';
const SIZE = 72;

// The most used emoji in short-form captions and titles: faces, hands, hearts, celebration, status
// marks, arrows, a few objects, flags, keycaps and the common skin-tone / ZWJ variants.
const EMOJI = [
  // faces
  '😀 😃 😄 😁 😆 😅 🤣 😂 🙂 🙃 🫠 😉 😊 😇 🥰 😍 🤩 😘 😋 😜 🤪 😎 🤓 🧐 🤗 🤭 🫡 🤫 🤔',
  '😐 😑 😶 😏 🙄 😬 😌 😔 🤤 😴 😷 🤢 🤮 🤧 🥵 🥶 🤯 🤠 🥳 🥹 😮 😲 😳 🥺 😢 😭 😱 😩 😫',
  '😤 😡 😈 💀 🤡 👻 👽 🤖 💩 😻 🙈',
  // hands & people
  '👍 👎 👏 🙌 🙏 👌 ✌️ 🤞 🤟 🤘 🤙 👋 💪 👊 ✊ ✋ 🖐️ 🤝 🫶 👉 👈 👆 👇 ☝️ 🫵 ✍️ 👀 🧠 🫂',
  '👍🏻 👍🏼 👍🏽 👍🏾 👍🏿 👏🏻 👏🏽 👏🏿 🙏🏻 🙏🏽 🙏🏿 💪🏻 💪🏽 💪🏿',
  '🤷 🤷‍♂️ 🤷‍♀️ 🤦 🤦‍♂️ 🤦‍♀️ 🙋 🙋‍♀️ 🙋‍♂️ 👨‍💻 👩‍💻 🏃 💃 🕺',
  // hearts
  '❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 💔 ❤️‍🔥 💕 💖 💗 💓 💘 💝 💞 💯',
  // celebration & status
  '🔥 ✨ ⭐ 🌟 💫 ⚡ 💥 🎉 🎊 🎁 🎈 🏆 🥇 🎯 🚀 💡 ✅ ✔️ ❌ ❗ ❓ ⚠️ 🆕 🆓 🔝',
  // arrows
  '➡️ ⬅️ ⬆️ ⬇️ ↗️ ↘️ 🔁 🔄',
  // objects & things
  '📈 📉 📊 📌 📍 🔔 📣 💬 💭 💰 💸 💵 💎 👑 🎵 🎶 🎬 🎥 📸 📱 💻 ⏰ ⏳ 🔗 🔒 🛒 🎮 📚',
  '🌈 ☀️ 🌙 🌍 🌊 🌸 🌹 🌻 🍀 🍕 🍔 ☕ 🍾 🥂 🍻 🎂 🐶 🐱 🦄 🦋 🐐 🏠 ✈️ 🚗 ⚽ 🏀',
  // flags & keycaps
  '🇺🇸 🇫🇷 🇬🇧 🇩🇪 🇪🇸 🇮🇹 🇯🇵 🇧🇷 🇨🇦 🇮🇳 🏳️‍🌈 1️⃣ 2️⃣ 3️⃣ #️⃣',
]
  .join(' ')
  .split(' ')
  .filter(Boolean);

const ZWJ = 0x200d;
const VS16 = 0xfe0f;

function codePointsOf(emoji: string): number[] {
  const points: number[] = [];

  for (const char of emoji) points.push(char.codePointAt(0) ?? 0);

  return points;
}

// Twemoji's file naming: U+FE0F is dropped unless the sequence is a ZWJ sequence.
function fileKey(emoji: string): string {
  const points = codePointsOf(emoji);
  const kept = points.includes(ZWJ) ? points : points.filter((point) => point !== VS16);

  return kept.map((point) => point.toString(16)).join('-');
}

function svgDirFromArgs(): string {
  const index = process.argv.indexOf('--svg-dir');

  if (index !== -1) return resolve(process.argv[index + 1]);

  const work = mkdtempSync(join(tmpdir(), 'leclap-emoji-'));
  const tarball = execFileSync('npm', ['pack', SVG_PACKAGE, '--silent'], { cwd: work, encoding: 'utf8' }).trim();

  execFileSync('tar', ['xzf', tarball], { cwd: work });

  return join(work, 'package');
}

function svgFor(svgDir: string, key: string): string | null {
  const candidates = [key, key.replace(/-fe0f/g, '')];
  const found = candidates.map((name) => join(svgDir, `${name}.svg`)).find((path) => existsSync(path));

  return found ? readFileSync(found, 'utf8') : null;
}

const svgDir = svgDirFromArgs();

mkdirSync(outDir, { recursive: true });

for (const file of readdirSync(outDir).filter((name) => name.endsWith('.png'))) rmSync(join(outDir, file));

const keys = [...new Set(EMOJI.map(fileKey))].sort();
const written: string[] = [];

for (const key of keys) {
  const svg = svgFor(svgDir, key);

  if (!svg) {
    console.warn(`  missing ${key}.svg — skipped`);
    continue;
  }

  const png = new Resvg(svg, { fitTo: { mode: 'width', value: SIZE } }).render().asPng();

  writeFileSync(join(outDir, `${key}.png`), png);
  written.push(key);
}

const manifest = `// GENERATED by scripts/gen-emoji.ts — do not edit.
// The colour emoji bundled as ${SIZE}px PNGs under @leclap/creative-kit/src/library/emoji/ (Twemoji, CC-BY 4.0),
// keyed by code-point sequence: lowercase hex joined by '-', U+FE0F dropped outside ZWJ sequences.

export const EMOJI_ASSET_SIZE = ${SIZE};

export const EMOJI_ASSET_KEYS: readonly string[] = [
${written.map((key) => `  '${key}',`).join('\n')}
];
`;

writeFileSync(manifestPath, manifest);
console.log(`✓ ${written.length} emoji → ${outDir}`);
