// Local Expo config plugin: pin the Android NDK to 27.1.x.
//
// React Native uses C++20 std::format (and reanimated uses C++20 concepts). Older Expo projects
// can retain NDK 26.1 (libc++ 17), where std::format is gated as incomplete → expo-modules-core
// and react-native-reanimated fail `buildCMakeDebug`. NDK 27.1 (libc++ 18) enables it. The
// android/ dir is CNG-regenerated by prebuild, so this plugin re-applies the version every time.
const { withProjectBuildGradle } = require('expo/config-plugins');

const NDK_VERSION = '27.1.12297006';

module.exports = function withNdkVersion(config) {
  return withProjectBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      return cfg;
    }

    if (/ndkVersion\s*=\s*"[^"]*"/.test(cfg.modResults.contents)) {
      cfg.modResults.contents = cfg.modResults.contents.replace(
        /ndkVersion\s*=\s*"[^"]*"/,
        `ndkVersion = "${NDK_VERSION}"`
      );
    }

    return cfg;
  });
};
