// AUTO-GENERATED by scripts/embed-templates.ts — do not edit by hand. Run `pnpm embed-templates`.
import type { TemplateDescriptor } from 'ffmpeg-video-composer';

export const builtinTemplates: Record<string, TemplateDescriptor> = {
  'fast-curious': {
    meta: {
      name: 'Fast & Curious',
      description: 'Punchy two-tone flash intro — your name on a bold cut, then your clip.',
    },
    global: {
      variables: {
        optionA1: 'Tea',
        optionB1: 'Coffee',
        optionA2: 'Beach',
        optionB2: 'Mountains',
        optionA3: 'Cats',
        optionB3: 'Dogs',
      },
      orientation: 'landscape',
      musicEnabled: true,
      music: {
        name: 'go-by-ocean.mp3',
      },
      transition: {
        type: 'fade',
        duration: 0.2,
      },
      audio: {
        sourceVolume: 1,
        musicVolume: 0.25,
        normalize: 'loudnorm',
      },
    },
    sections: [
      {
        name: 'form_1',
        type: 'form',
        title: {
          en: "Who's the star?",
        },
        description: {
          en: '',
        },
        options: {
          fields: [
            {
              name: 'form_1_firstname',
              maxLength: 20,
              label: {
                en: 'First name',
              },
            },
          ],
        },
      },
      {
        type: 'partial',
        ref: 'flash-card',
        prefix: 'q1_',
        variables: {
          optionA: '{{ optionA1 }}',
          optionB: '{{ optionB1 }}',
        },
      },
      {
        name: 'video_1',
        type: 'project_video',
        look: 'vivid',
        title: {
          en: 'Answer #1',
        },
        description: {
          en: '{{ optionA1 }} or {{ optionB1 }}? — film your answer',
        },
        options: {
          duration: 20,
          forceAspectRatio: true,
          countdown: true,
          countdownDuration: 2,
          musicVolume: 0.1,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 600,
              w: 1280,
              h: 120,
              c: '#141416@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 80,
              y: 628,
              w: 90,
              h: 5,
              c: '#ff2e4d@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ optionA1 }} or {{ optionB1 }}?',
              },
              fontcolor: '#f5f5f0',
              fontsize: 44,
              x: 80,
              y: 644,
              fontfile: 'BebasNeue.ttf',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#141416',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#141416',
            },
          },
        ],
      },
      {
        type: 'partial',
        ref: 'flash-card',
        prefix: 'q2_',
        variables: {
          optionA: '{{ optionA2 }}',
          optionB: '{{ optionB2 }}',
        },
      },
      {
        name: 'video_2',
        type: 'project_video',
        look: 'vivid',
        title: {
          en: 'Answer #2',
        },
        description: {
          en: '{{ optionA2 }} or {{ optionB2 }}? — film your answer',
        },
        options: {
          duration: 20,
          forceAspectRatio: true,
          countdown: true,
          countdownDuration: 2,
          musicVolume: 0.1,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 600,
              w: 1280,
              h: 120,
              c: '#141416@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 80,
              y: 628,
              w: 90,
              h: 5,
              c: '#ff2e4d@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ optionA2 }} or {{ optionB2 }}?',
              },
              fontcolor: '#f5f5f0',
              fontsize: 44,
              x: 80,
              y: 644,
              fontfile: 'BebasNeue.ttf',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#141416',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#141416',
            },
          },
        ],
      },
      {
        type: 'partial',
        ref: 'flash-card',
        prefix: 'q3_',
        variables: {
          optionA: '{{ optionA3 }}',
          optionB: '{{ optionB3 }}',
        },
      },
      {
        name: 'video_3',
        type: 'project_video',
        look: 'vivid',
        title: {
          en: 'Answer #3',
        },
        description: {
          en: '{{ optionA3 }} or {{ optionB3 }}? — film your answer',
        },
        options: {
          duration: 20,
          forceAspectRatio: true,
          countdown: true,
          countdownDuration: 2,
          musicVolume: 0.1,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 600,
              w: 1280,
              h: 120,
              c: '#141416@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 80,
              y: 628,
              w: 90,
              h: 5,
              c: '#ff2e4d@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ optionA3 }} or {{ optionB3 }}?',
              },
              fontcolor: '#f5f5f0',
              fontsize: 44,
              x: 80,
              y: 644,
              fontfile: 'BebasNeue.ttf',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#141416',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#141416',
            },
          },
        ],
      },
      {
        type: 'partial',
        ref: 'logo-bumper',
      },
    ],
  } as TemplateDescriptor,
  intro: {
    meta: {
      name: 'Intro',
      description: 'Cinematic title card — bold name, accent rule, graded backdrop.',
    },
    global: {
      orientation: 'landscape',
      musicEnabled: true,
      music: {
        name: 'arcadia.mp3',
      },
      transition: {
        type: 'fade',
        duration: 0.5,
      },
      audio: {
        sourceVolume: 1,
        normalize: 'loudnorm',
      },
    },
    sections: [
      {
        name: 'form_1',
        type: 'form',
        title: {
          en: 'Title card details',
        },
        description: {
          en: '',
        },
        options: {
          fields: [
            {
              name: 'form_1_firstname',
              maxLength: 20,
              label: {
                en: 'First name',
              },
            },
            {
              name: 'form_1_lastname',
              maxLength: 20,
              label: {
                en: 'Last name',
              },
            },
            {
              name: 'form_1_job',
              maxLength: 40,
              label: {
                en: 'Role / subtitle',
              },
            },
          ],
        },
      },
      {
        name: 'premium_intro',
        type: 'color_background',
        options: {
          backgroundColor: '#0d1b2a',
          duration: 4,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#0d1b2a@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 160,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 560,
              w: 1280,
              h: 160,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_firstname }} {{ form_1_lastname }}',
              },
              fontcolor: '#f5c518',
              fontsize: 132,
              x: '(w-text_w)/2',
              y: 248,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.5),0,if(lt(t,1.4),(t-0.5)/0.9,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 490,
              y: 412,
              w: 300,
              h: 5,
              c: '#f5c518@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_job }}',
              },
              fontcolor: '#e8eef7',
              fontsize: 34,
              x: '(w-text_w)/2',
              y: 446,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,1.0),0,if(lt(t,1.8),(t-1.0)/0.8,1))'",
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#0d1b2a',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#0d1b2a',
            },
          },
        ],
      },
      {
        name: 'video_1',
        type: 'project_video',
        look: 'cinematic',
        title: {
          en: 'Record your clip',
        },
        description: {
          en: 'Your moment — graded in the title-card palette',
        },
        options: {
          duration: 30,
          forceAspectRatio: true,
          framingGuide: {
            type: 'silhouette',
            position: 'center',
          },
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 600,
              w: 1280,
              h: 120,
              c: '#0d1b2a@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 80,
              y: 628,
              w: 90,
              h: 5,
              c: '#f5c518@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_firstname }}',
              },
              fontcolor: '#f5c518',
              fontsize: 52,
              x: 80,
              y: 644,
              fontfile: 'BebasNeue.ttf',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#0d1b2a',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#0d1b2a',
            },
          },
        ],
      },
    ],
  } as TemplateDescriptor,
  'landscape-spotlight': {
    meta: {
      name: 'Landscape Spotlight',
      description: 'Record a clip — graded intro + outro wrap it into a polished video.',
    },
    global: {
      orientation: 'landscape',
      musicEnabled: true,
      music: {
        name: 'arcadia.mp3',
      },
      transition: {
        type: 'fade',
        duration: 0.5,
      },
      audio: {
        sourceVolume: 1,
      },
    },
    sections: [
      {
        name: 'form_1',
        type: 'form',
        title: {
          en: 'Your details',
        },
        description: {
          en: '',
        },
        options: {
          fields: [
            {
              name: 'form_1_name',
              maxLength: 24,
              label: {
                en: 'Your name',
              },
            },
          ],
        },
      },
      {
        name: 'intro',
        type: 'color_background',
        transition: {
          type: 'wipeleft',
          duration: 0.4,
        },
        options: {
          backgroundColor: '#0d1b2a',
          duration: 2.4,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 720,
              c: '#0d1b2a@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 1280,
              h: 150,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 570,
              w: 1280,
              h: 150,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'PRESENTING',
              },
              fontcolor: '#e8eef7',
              fontsize: 30,
              x: '(w-text_w)/2',
              y: 250,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,0.3),0,if(lt(t,1.0),(t-0.3)/0.7,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_name }}',
              },
              fontcolor: '#7C83FD',
              fontsize: 124,
              x: '(w-text_w)/2',
              y: 320,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.6),0,if(lt(t,1.5),(t-0.6)/0.9,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 540,
              y: 470,
              w: 200,
              h: 5,
              c: '#7C83FD@1',
              t: 'fill',
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#0d1b2a',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#0d1b2a',
            },
          },
        ],
      },
      {
        name: 'video_1',
        type: 'project_video',
        look: 'cinematic',
        title: {
          en: 'Record your clip',
        },
        description: {
          en: 'Your moment — graded and captioned',
        },
        options: {
          duration: 30,
          forceAspectRatio: true,
          countdown: true,
          countdownDuration: 2,
          musicVolume: 0.1,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 600,
              w: 1280,
              h: 120,
              c: '#0d1b2a@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 80,
              y: 628,
              w: 90,
              h: 5,
              c: '#7C83FD@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_name }}',
              },
              fontcolor: '#7C83FD',
              fontsize: 52,
              x: 80,
              y: 644,
              fontfile: 'BebasNeue.ttf',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#0d1b2a',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#0d1b2a',
            },
          },
        ],
      },
      {
        type: 'partial',
        ref: 'logo-bumper',
      },
    ],
  } as TemplateDescriptor,
  'portrait-spotlight': {
    meta: {
      name: 'Portrait Spotlight',
      description: 'Record a vertical clip — graded intro + outro wrap it into a polished video.',
    },
    global: {
      orientation: 'portrait',
      musicEnabled: true,
      music: {
        name: 'arcadia.mp3',
      },
      transition: {
        type: 'fade',
        duration: 0.5,
      },
      audio: {
        sourceVolume: 1,
      },
    },
    sections: [
      {
        name: 'form_1',
        type: 'form',
        title: {
          en: 'Your details',
        },
        description: {
          en: '',
        },
        options: {
          fields: [
            {
              name: 'form_1_name',
              maxLength: 24,
              label: {
                en: 'Your name',
              },
            },
          ],
        },
      },
      {
        name: 'intro',
        type: 'color_background',
        transition: {
          type: 'wipeleft',
          duration: 0.4,
        },
        options: {
          backgroundColor: '#0d1b2a',
          duration: 2.4,
        },
        filters: [
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 1280,
              c: '#0d1b2a@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 0,
              w: 720,
              h: 220,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 1060,
              w: 720,
              h: 220,
              c: '#13243f@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: 'PRESENTING',
              },
              fontcolor: '#e8eef7',
              fontsize: 34,
              x: '(w-text_w)/2',
              y: 470,
              fontfile: 'Oswald.ttf',
              alpha: "'if(lt(t,0.3),0,if(lt(t,1.0),(t-0.3)/0.7,1))'",
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_name }}',
              },
              fontcolor: '#7C83FD',
              fontsize: 120,
              x: '(w-text_w)/2',
              y: 560,
              fontfile: 'BebasNeue.ttf',
              alpha: "'if(lt(t,0.6),0,if(lt(t,1.5),(t-0.6)/0.9,1))'",
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 260,
              y: 740,
              w: 200,
              h: 5,
              c: '#7C83FD@1',
              t: 'fill',
            },
          },
          {
            type: 'vignette',
          },
          {
            type: 'fade',
            values: {
              t: 'in',
              d: '0.6',
              color: '#0d1b2a',
            },
          },
          {
            type: 'fade',
            values: {
              t: 'out',
              d: '{{ transitionDuration }}',
              st: '{{ transitionStartTime }}',
              color: '#0d1b2a',
            },
          },
        ],
      },
      {
        name: 'video_1',
        type: 'project_video',
        look: 'cinematic',
        title: {
          en: 'Record your clip',
        },
        description: {
          en: 'Your moment — graded and captioned',
        },
        options: {
          duration: 30,
          forceAspectRatio: true,
          countdown: true,
          countdownDuration: 2,
          musicVolume: 0.1,
        },
        filters: [
          {
            type: 'vignette',
          },
          {
            type: 'drawbox',
            values: {
              x: 0,
              y: 1100,
              w: 720,
              h: 180,
              c: '#0d1b2a@0.55',
              t: 'fill',
            },
          },
          {
            type: 'drawbox',
            values: {
              x: 60,
              y: 1150,
              w: 90,
              h: 5,
              c: '#7C83FD@1',
              t: 'fill',
            },
          },
          {
            type: 'drawtext',
            values: {
              text: {
                en: '{{ form_1_name }}',
              },
              fontcolor: '#7C83FD',
              fontsize: 52,
              x: 60,
              y: 1166,
              fontfile: 'BebasNeue.ttf',
            },
          },
          {
            type: 'fadein',
            values: {
              color: '#0d1b2a',
            },
          },
          {
            type: 'fadeout',
            values: {
              color: '#0d1b2a',
            },
          },
        ],
      },
      {
        type: 'partial',
        ref: 'logo-bumper-portrait',
      },
    ],
  } as TemplateDescriptor,
};
